"object"!==typeof JSON&&(JSON={});
(function(){function l(k){return 10>k?"0"+k:k}function k(k){v.lastIndex=0;return v.test(k)?'"'+k.replace(v,function(k){var l=V[k];return"string"===typeof l?l:"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+k+'"'}function A(l,R){var s,D,p,v,P=r,J,w=R[l];w&&("object"===typeof w&&"function"===typeof w.toJSON)&&(w=w.toJSON(l));"function"===typeof z&&(w=z.call(R,l,w));switch(typeof w){case "string":return k(w);case "number":return isFinite(w)?String(w):"null";case "boolean":case "null":return String(w);
case "object":if(!w)return"null";r+=F;J=[];if("[object Array]"===Object.prototype.toString.apply(w)){v=w.length;for(s=0;s<v;s+=1)J[s]=A(s,w)||"null";p=0===J.length?"[]":r?"[\n"+r+J.join(",\n"+r)+"\n"+P+"]":"["+J.join(",")+"]";r=P;return p}if(z&&"object"===typeof z){v=z.length;for(s=0;s<v;s+=1)"string"===typeof z[s]&&(D=z[s],(p=A(D,w))&&J.push(k(D)+(r?": ":":")+p))}else for(D in w)Object.prototype.hasOwnProperty.call(w,D)&&(p=A(D,w))&&J.push(k(D)+(r?": ":":")+p);p=0===J.length?"{}":r?"{\n"+r+J.join(",\n"+
r)+"\n"+P+"}":"{"+J.join(",")+"}";r=P;return p}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+l(this.getUTCMonth()+1)+"-"+l(this.getUTCDate())+"T"+l(this.getUTCHours())+":"+l(this.getUTCMinutes())+":"+l(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var p=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
v=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,r,F,V={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},z;"function"!==typeof JSON.stringify&&(JSON.stringify=function(k,l,s){var p;F=r="";if(typeof s==="number")for(p=0;p<s;p=p+1)F=F+" ";else typeof s==="string"&&(F=s);if((z=l)&&typeof l!=="function"&&(typeof l!=="object"||typeof l.length!=="number"))throw Error("JSON.stringify");return A("",{"":k})});
"function"!==typeof JSON.parse&&(JSON.parse=function(k,l){function s(k,p){var r,z,w=k[p];if(w&&typeof w==="object")for(r in w)if(Object.prototype.hasOwnProperty.call(w,r)){z=s(w,r);z!==void 0?w[r]=z:delete w[r]}return l.call(k,p,w)}var r,k=String(k);p.lastIndex=0;p.test(k)&&(k=k.replace(p,function(k){return"\\u"+("0000"+k.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(k.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){r=eval("("+k+")");return typeof l==="function"?s({"":r},""):r}throw new SyntaxError("JSON.parse");})})();
(function(l,k){function A(a,b,d){if(d===k&&1===a.nodeType)if(d="data-"+b.replace(pc,"-$1").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{d="true"===d?!0:"false"===d?!1:"null"===d?null:+d+""===d?+d:qc.test(d)?c.parseJSON(d):d}catch(e){}c.data(a,b,d)}else d=k;return d}function p(a){for(var b in a)if(!("data"===b&&c.isEmptyObject(a[b]))&&"toJSON"!==b)return!1;return!0}function v(){return!1}function r(){return!0}function F(a){return!a||!a.parentNode||11===a.parentNode.nodeType}function V(a,
b){do a=a[b];while(a&&1!==a.nodeType);return a}function z(a,b,d){b=b||0;if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)===d});if(b.nodeType)return c.grep(a,function(a){return a===b===d});if("string"===typeof b){var e=c.grep(a,function(a){return 1===a.nodeType});if(rc.test(b))return c.filter(b,e,!d);b=c.filter(b,e)}return c.grep(a,function(a){return 0<=c.inArray(a,b)===d})}function B(a){var b=ob.split("|"),a=a.createDocumentFragment();if(a.createElement)for(;b.length;)a.createElement(b.pop());
return a}function R(a,b){if(1===b.nodeType&&c.hasData(a)){var d,e,f;e=c._data(a);var g=c._data(b,e),h=e.events;if(h)for(d in delete g.handle,g.events={},h){e=0;for(f=h[d].length;e<f;e++)c.event.add(b,d,h[d][e])}g.data&&(g.data=c.extend({},g.data))}}function s(a,b){var d;if(1===b.nodeType){b.clearAttributes&&b.clearAttributes();b.mergeAttributes&&b.mergeAttributes(a);d=b.nodeName.toLowerCase();if("object"===d){if(b.parentNode&&(b.outerHTML=a.outerHTML),c.support.html5Clone&&a.innerHTML&&!c.trim(b.innerHTML))b.innerHTML=
a.innerHTML}else"input"===d&&pb.test(a.type)?(b.defaultChecked=b.checked=a.checked,b.value!==a.value&&(b.value=a.value)):"option"===d?b.selected=a.defaultSelected:"input"===d||"textarea"===d?b.defaultValue=a.defaultValue:"script"===d&&b.text!==a.text&&(b.text=a.text);b.removeAttribute(c.expando)}}function D(a){return"undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName("*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll("*"):[]}function mb(a){pb.test(a.type)&&(a.defaultChecked=
a.checked)}function nb(a,b){if(b in a)return b;for(var d=b.charAt(0).toUpperCase()+b.slice(1),c=b,f=qb.length;f--;)if(b=qb[f]+d,b in a)return b;return c}function P(a,b){a=b||a;return"none"===c.css(a,"display")||!c.contains(a.ownerDocument,a)}function J(a,b){for(var d,e,f=[],g=0,h=a.length;g<h;g++)d=a[g],d.style&&(f[g]=c._data(d,"olddisplay"),b?(!f[g]&&"none"===d.style.display&&(d.style.display=""),""===d.style.display&&P(d)&&(f[g]=c._data(d,"olddisplay",rb(d.nodeName)))):(e=G(d,"display"),!f[g]&&
"none"!==e&&c._data(d,"olddisplay",e)));for(g=0;g<h;g++)if(d=a[g],d.style&&(!b||"none"===d.style.display||""===d.style.display))d.style.display=b?f[g]||"":"none";return a}function w(a,b,d){return(a=sc.exec(b))?Math.max(0,a[1]-(d||0))+(a[2]||"px"):b}function sb(a,b,d,e){for(var b=d===(e?"border":"content")?4:"width"===b?1:0,f=0;4>b;b+=2)"margin"===d&&(f+=c.css(a,d+W[b],!0)),e?("content"===d&&(f-=parseFloat(G(a,"padding"+W[b]))||0),"margin"!==d&&(f-=parseFloat(G(a,"border"+W[b]+"Width"))||0)):(f+=parseFloat(G(a,
"padding"+W[b]))||0,"padding"!==d&&(f+=parseFloat(G(a,"border"+W[b]+"Width"))||0));return f}function tb(a,b,d){var e="width"===b?a.offsetWidth:a.offsetHeight,f=!0,g=c.support.boxSizing&&"border-box"===c.css(a,"boxSizing");if(0>=e||null==e){e=G(a,b);if(0>e||null==e)e=a.style[b];if(oa.test(e))return e;f=g&&(c.support.boxSizingReliable||e===a.style[b]);e=parseFloat(e)||0}return e+sb(a,b,d||(g?"border":"content"),f)+"px"}function rb(a){if(Na[a])return Na[a];var b=c("<"+a+">").appendTo(o.body),d=b.css("display");
b.remove();if("none"===d||""===d){da=o.body.appendChild(da||c.extend(o.createElement("iframe"),{frameBorder:0,width:0,height:0}));if(!ea||!da.createElement)ea=(da.contentWindow||da.contentDocument).document,ea.write("<!doctype html><html><body>"),ea.close();b=ea.body.appendChild(ea.createElement(a));d=G(b,"display");o.body.removeChild(da)}return Na[a]=d}function Oa(a,b,d,e){var f;if(c.isArray(b))c.each(b,function(b,c){d||tc.test(a)?e(a,c):Oa(a+"["+("object"===typeof c?b:"")+"]",c,d,e)});else if(!d&&
"object"===c.type(b))for(f in b)Oa(a+"["+f+"]",b[f],d,e);else e(a,b)}function ub(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e,f,g=b.toLowerCase().split(X),h=0,i=g.length;if(c.isFunction(d))for(;h<i;h++)e=g[h],(f=/^\+/.test(e))&&(e=e.substr(1)||"*"),e=a[e]=a[e]||[],e[f?"unshift":"push"](d)}}function pa(a,b,d,c,f,g){f=f||b.dataTypes[0];g=g||{};g[f]=!0;for(var h,f=a[f],i=0,j=f?f.length:0,m=a===Pa;i<j&&(m||!h);i++)h=f[i](b,d,c),"string"===typeof h&&(!m||g[h]?h=k:(b.dataTypes.unshift(h),
h=pa(a,b,d,c,h,g)));if((m||!h)&&!g["*"])h=pa(a,b,d,c,"*",g);return h}function vb(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)b[d]!==k&&((f[d]?a:e||(e={}))[d]=b[d]);e&&c.extend(!0,a,e)}function wb(){try{return new l.XMLHttpRequest}catch(a){}}function xb(){setTimeout(function(){qa=k},0);return qa=c.now()}function yb(a,b,d){var e,f=0,g=ra.length,h=c.Deferred().always(function(){delete i.elem}),i=function(){for(var b=qa||xb(),b=Math.max(0,j.startTime+j.duration-b),d=1-(b/j.duration||0),c=
0,e=j.tweens.length;c<e;c++)j.tweens[c].run(d);h.notifyWith(a,[j,d,b]);if(1>d&&e)return b;h.resolveWith(a,[j]);return!1},j=h.promise({elem:a,props:c.extend({},b),opts:c.extend(!0,{specialEasing:{}},d),originalProperties:b,originalOptions:d,startTime:qa||xb(),duration:d.duration,tweens:[],createTween:function(b,d){var e=c.Tween(a,j.opts,b,d,j.opts.specialEasing[b]||j.opts.easing);j.tweens.push(e);return e},stop:function(b){for(var d=0,c=b?j.tweens.length:0;d<c;d++)j.tweens[d].run(1);b?h.resolveWith(a,
[j,b]):h.rejectWith(a,[j,b]);return this}}),b=j.props,d=j.opts.specialEasing,m,q,n,k;for(e in b)if(m=c.camelCase(e),q=d[m],n=b[e],c.isArray(n)&&(q=n[1],n=b[e]=n[0]),e!==m&&(b[m]=n,delete b[e]),(k=c.cssHooks[m])&&"expand"in k)for(e in n=k.expand(n),delete b[m],n)e in b||(b[e]=n[e],d[e]=q);else d[m]=q;for(;f<g;f++)if(e=ra[f].call(j,a,b,j.opts))return e;var l=j;c.each(b,function(a,b){for(var d=(ka[a]||[]).concat(ka["*"]),c=0,e=d.length;c<e&&!d[c].call(l,a,b);c++);});c.isFunction(j.opts.start)&&j.opts.start.call(a,
j);c.fx.timer(c.extend(i,{anim:j,queue:j.opts.queue,elem:a}));return j.progress(j.opts.progress).done(j.opts.done,j.opts.complete).fail(j.opts.fail).always(j.opts.always)}function H(a,b,d,c,f){return new H.prototype.init(a,b,d,c,f)}function sa(a,b){for(var d,c={height:a},f=0,b=b?1:0;4>f;f+=2-b)d=W[f],c["margin"+d]=c["padding"+d]=a;b&&(c.opacity=c.width=a);return c}function zb(a){return c.isWindow(a)?a:9===a.nodeType?a.defaultView||a.parentWindow:!1}var Ab,ta,o=l.document,vc=l.location,wc=l.navigator,
xc=l.jQuery,yc=l.$,Bb=Array.prototype.push,Q=Array.prototype.slice,Cb=Array.prototype.indexOf,zc=Object.prototype.toString,Qa=Object.prototype.hasOwnProperty,Ra=String.prototype.trim,c=function(a,b){return new c.fn.init(a,b,Ab)},ua=/[\-+]?(?:\d*\.|)\d+(?:[eE][\-+]?\d+|)/.source,Ac=/\S/,X=/\s+/,Bc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,Cc=/^(?:[^#<]*(<[\w\W]+>)[^>]*$|#([\w\-]*)$)/,Db=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,Dc=/^[\],:{}\s]*$/,Ec=/(?:^|:|,)(?:\s*\[)+/g,Fc=/\\(?:["\\\/bfnrt]|u[\da-fA-F]{4})/g,Gc=
/"[^"\\\r\n]*"|true|false|null|-?(?:\d\d*\.|)\d+(?:[eE][\-+]?\d+|)/g,Hc=/^-ms-/,Ic=/-([\da-z])/gi,Jc=function(a,b){return(b+"").toUpperCase()},va=function(){o.addEventListener?(o.removeEventListener("DOMContentLoaded",va,!1),c.ready()):"complete"===o.readyState&&(o.detachEvent("onreadystatechange",va),c.ready())},Eb={};c.fn=c.prototype={constructor:c,init:function(a,b,d){var e;if(!a)return this;if(a.nodeType)return this.context=this[0]=a,this.length=1,this;if("string"===typeof a){if((e="<"===a.charAt(0)&&
">"===a.charAt(a.length-1)&&3<=a.length?[null,a,null]:Cc.exec(a))&&(e[1]||!b)){if(e[1])return a=(b=b instanceof c?b[0]:b)&&b.nodeType?b.ownerDocument||b:o,a=c.parseHTML(e[1],a,!0),Db.test(e[1])&&c.isPlainObject(b)&&this.attr.call(a,b,!0),c.merge(this,a);if((b=o.getElementById(e[2]))&&b.parentNode){if(b.id!==e[2])return d.find(a);this.length=1;this[0]=b}this.context=o;this.selector=a;return this}return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a)}if(c.isFunction(a))return d.ready(a);a.selector!==
k&&(this.selector=a.selector,this.context=a.context);return c.makeArray(a,this)},selector:"",jquery:"1.8.2",length:0,size:function(){return this.length},toArray:function(){return Q.call(this)},get:function(a){return null==a?this.toArray():0>a?this[this.length+a]:this[a]},pushStack:function(a,b,d){a=c.merge(this.constructor(),a);a.prevObject=this;a.context=this.context;"find"===b?a.selector=this.selector+(this.selector?" ":"")+d:b&&(a.selector=this.selector+"."+b+"("+d+")");return a},each:function(a,
b){return c.each(this,a,b)},ready:function(a){c.ready.promise().done(a);return this},eq:function(a){a=+a;return-1===a?this.slice(a):this.slice(a,a+1)},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},slice:function(){return this.pushStack(Q.apply(this,arguments),"slice",Q.call(arguments).join(","))},map:function(a){return this.pushStack(c.map(this,function(b,d){return a.call(b,d,b)}))},end:function(){return this.prevObject||this.constructor(null)},push:Bb,sort:[].sort,splice:[].splice};
c.fn.init.prototype=c.fn;c.extend=c.fn.extend=function(){var a,b,d,e,f,g=arguments[0]||{},h=1,i=arguments.length,j=!1;"boolean"===typeof g&&(j=g,g=arguments[1]||{},h=2);"object"!==typeof g&&!c.isFunction(g)&&(g={});i===h&&(g=this,--h);for(;h<i;h++)if(null!=(a=arguments[h]))for(b in a)d=g[b],e=a[b],g!==e&&(j&&e&&(c.isPlainObject(e)||(f=c.isArray(e)))?(f?(f=!1,d=d&&c.isArray(d)?d:[]):d=d&&c.isPlainObject(d)?d:{},g[b]=c.extend(j,d,e)):e!==k&&(g[b]=e));return g};c.extend({noConflict:function(a){l.$===
c&&(l.$=yc);a&&l.jQuery===c&&(l.jQuery=xc);return c},isReady:!1,readyWait:1,holdReady:function(a){a?c.readyWait++:c.ready(!0)},ready:function(a){if(!(!0===a?--c.readyWait:c.isReady)){if(!o.body)return setTimeout(c.ready,1);c.isReady=!0;!0!==a&&0<--c.readyWait||(ta.resolveWith(o,[c]),c.fn.trigger&&c(o).trigger("ready").off("ready"))}},isFunction:function(a){return"function"===c.type(a)},isArray:Array.isArray||function(a){return"array"===c.type(a)},isWindow:function(a){return null!=a&&a==a.window},
isNumeric:function(a){return!isNaN(parseFloat(a))&&isFinite(a)},type:function(a){return null==a?String(a):Eb[zc.call(a)]||"object"},isPlainObject:function(a){if(!a||"object"!==c.type(a)||a.nodeType||c.isWindow(a))return!1;try{if(a.constructor&&!Qa.call(a,"constructor")&&!Qa.call(a.constructor.prototype,"isPrototypeOf"))return!1}catch(b){return!1}for(var d in a);return d===k||Qa.call(a,d)},isEmptyObject:function(a){for(var b in a)return!1;return!0},error:function(a){throw Error(a);},parseHTML:function(a,
b,d){var e;if(!a||"string"!==typeof a)return null;"boolean"===typeof b&&(d=b,b=0);b=b||o;if(e=Db.exec(a))return[b.createElement(e[1])];e=c.buildFragment([a],b,d?null:[]);return c.merge([],(e.cacheable?c.clone(e.fragment):e.fragment).childNodes)},parseJSON:function(a){if(!a||"string"!==typeof a)return null;a=c.trim(a);if(l.JSON&&l.JSON.parse)return l.JSON.parse(a);if(Dc.test(a.replace(Fc,"@").replace(Gc,"]").replace(Ec,"")))return(new Function("return "+a))();c.error("Invalid JSON: "+a)},parseXML:function(a){var b,
d;if(!a||"string"!==typeof a)return null;try{l.DOMParser?(d=new DOMParser,b=d.parseFromString(a,"text/xml")):(b=new ActiveXObject("Microsoft.XMLDOM"),b.async="false",b.loadXML(a))}catch(e){b=k}(!b||!b.documentElement||b.getElementsByTagName("parsererror").length)&&c.error("Invalid XML: "+a);return b},noop:function(){},globalEval:function(a){a&&Ac.test(a)&&(l.execScript||function(a){l.eval.call(l,a)})(a)},camelCase:function(a){return a.replace(Hc,"ms-").replace(Ic,Jc)},nodeName:function(a,b){return a.nodeName&&
a.nodeName.toLowerCase()===b.toLowerCase()},each:function(a,b,d){var e,f=0,g=a.length,h=g===k||c.isFunction(a);if(d)if(h)for(e in a){if(!1===b.apply(a[e],d))break}else for(;f<g&&!1!==b.apply(a[f++],d););else if(h)for(e in a){if(!1===b.call(a[e],e,a[e]))break}else for(;f<g&&!1!==b.call(a[f],f,a[f++]););return a},trim:Ra&&!Ra.call("\ufeff\u00a0")?function(a){return null==a?"":Ra.call(a)}:function(a){return null==a?"":(a+"").replace(Bc,"")},makeArray:function(a,b){var d,e=b||[];null!=a&&(d=c.type(a),
null==a.length||"string"===d||"function"===d||"regexp"===d||c.isWindow(a)?Bb.call(e,a):c.merge(e,a));return e},inArray:function(a,b,d){var c;if(b){if(Cb)return Cb.call(b,a,d);c=b.length;for(d=d?0>d?Math.max(0,c+d):d:0;d<c;d++)if(d in b&&b[d]===a)return d}return-1},merge:function(a,b){var d=b.length,c=a.length,f=0;if("number"===typeof d)for(;f<d;f++)a[c++]=b[f];else for(;b[f]!==k;)a[c++]=b[f++];a.length=c;return a},grep:function(a,b,d){for(var c,f=[],g=0,h=a.length,d=!!d;g<h;g++)c=!!b(a[g],g),d!==
c&&f.push(a[g]);return f},map:function(a,b,d){var e,f,g=[],h=0,i=a.length;if(a instanceof c||i!==k&&"number"===typeof i&&(0<i&&a[0]&&a[i-1]||0===i||c.isArray(a)))for(;h<i;h++)e=b(a[h],h,d),null!=e&&(g[g.length]=e);else for(f in a)e=b(a[f],f,d),null!=e&&(g[g.length]=e);return g.concat.apply([],g)},guid:1,proxy:function(a,b){var d,e;"string"===typeof b&&(d=a[b],b=a,a=d);if(!c.isFunction(a))return k;e=Q.call(arguments,2);d=function(){return a.apply(b,e.concat(Q.call(arguments)))};d.guid=a.guid=a.guid||
c.guid++;return d},access:function(a,b,d,e,f,g,h){var i,j=null==d,m=0,q=a.length;if(d&&"object"===typeof d){for(m in d)c.access(a,b,m,d[m],1,g,e);f=1}else if(e!==k){i=h===k&&c.isFunction(e);j&&(i?(i=b,b=function(a,b,d){return i.call(c(a),d)}):(b.call(a,e),b=null));if(b)for(;m<q;m++)b(a[m],d,i?e.call(a[m],m,b(a[m],d)):e,h);f=1}return f?a:j?b.call(a):q?b(a[0],d):g},now:function(){return(new Date).getTime()}});c.ready.promise=function(a){if(!ta)if(ta=c.Deferred(),"complete"===o.readyState)setTimeout(c.ready,
1);else if(o.addEventListener)o.addEventListener("DOMContentLoaded",va,!1),l.addEventListener("load",c.ready,!1);else{o.attachEvent("onreadystatechange",va);l.attachEvent("onload",c.ready);var b=!1;try{b=null==l.frameElement&&o.documentElement}catch(d){}b&&b.doScroll&&function f(){if(!c.isReady){try{b.doScroll("left")}catch(a){return setTimeout(f,50)}c.ready()}}()}return ta.promise(a)};c.each("Boolean Number String Function Array Date RegExp Object".split(" "),function(a,b){Eb["[object "+b+"]"]=b.toLowerCase()});
Ab=c(o);var Fb={};c.Callbacks=function(a){var b;if("string"===typeof a){if(!(b=Fb[a])){b=a;var d=Fb[b]={};c.each(b.split(X),function(a,b){d[b]=!0});b=d}}else b=c.extend({},a);var a=b,e,f,g,h,i,j,m=[],q=!a.once&&[],n=function(b){e=a.memory&&b;f=!0;j=h||0;h=0;i=m.length;for(g=!0;m&&j<i;j++)if(!1===m[j].apply(b[0],b[1])&&a.stopOnFalse){e=!1;break}g=!1;m&&(q?q.length&&n(q.shift()):e?m=[]:l.disable())},l={add:function(){if(m){var b=m.length;(function uc(b){c.each(b,function(b,d){var e=c.type(d);"function"===
e&&(!a.unique||!l.has(d))?m.push(d):d&&(d.length&&"string"!==e)&&uc(d)})})(arguments);g?i=m.length:e&&(h=b,n(e))}return this},remove:function(){m&&c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,m,d));)m.splice(d,1),g&&(d<=i&&i--,d<=j&&j--)});return this},has:function(a){return-1<c.inArray(a,m)},empty:function(){m=[];return this},disable:function(){m=q=e=k;return this},disabled:function(){return!m},lock:function(){q=k;e||l.disable();return this},locked:function(){return!q},fireWith:function(a,
b){b=b||[];b=[a,b.slice?b.slice():b];if(m&&(!f||q))g?q.push(b):n(b);return this},fire:function(){l.fireWith(this,arguments);return this},fired:function(){return!!f}};return l};c.extend({Deferred:function(a){var b=[["resolve","done",c.Callbacks("once memory"),"resolved"],["reject","fail",c.Callbacks("once memory"),"rejected"],["notify","progress",c.Callbacks("memory")]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},then:function(){var a=
arguments;return c.Deferred(function(d){c.each(b,function(b,e){var m=e[0],q=a[b];f[e[1]](c.isFunction(q)?function(){var a=q.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().done(d.resolve).fail(d.reject).progress(d.notify);else d[m+"With"](this===f?d:this,[a])}:d[m])});a=null}).promise()},promise:function(a){return null!=a?c.extend(a,e):e}},f={};e.pipe=e.then;c.each(b,function(a,c){var i=c[2],j=c[3];e[c[1]]=i.add;j&&i.add(function(){d=j},b[a^1][2].disable,b[2][2].lock);f[c[0]]=i.fire;
f[c[0]+"With"]=i.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=0,d=Q.call(arguments),e=d.length,f=1!==e||a&&c.isFunction(a.promise)?e:0,g=1===f?a:c.Deferred(),h=function(a,b,d){return function(c){b[a]=this;d[a]=1<arguments.length?Q.call(arguments):c;d===i?g.notifyWith(b,d):--f||g.resolveWith(b,d)}},i,j,m;if(1<e){i=Array(e);j=Array(e);for(m=Array(e);b<e;b++)d[b]&&c.isFunction(d[b].promise)?d[b].promise().done(h(b,m,d)).fail(g.reject).progress(h(b,j,i)):--f}f||g.resolveWith(m,
d);return g.promise()}});var Kc=c,Sa;var E,wa,Y,xa,ya,I,Z,za,Ta,fa,Gb,x=o.createElement("div");x.setAttribute("className","t");x.innerHTML="  <link/><table></table><a href='/a'>a</a><input type='checkbox'/>";wa=x.getElementsByTagName("*");Y=x.getElementsByTagName("a")[0];Y.style.cssText="top:1px;float:left;opacity:.5";if(!wa||!wa.length)Sa={};else{xa=o.createElement("select");ya=xa.appendChild(o.createElement("option"));I=x.getElementsByTagName("input")[0];E={leadingWhitespace:3===x.firstChild.nodeType,
tbody:!x.getElementsByTagName("tbody").length,htmlSerialize:!!x.getElementsByTagName("link").length,style:/top/.test(Y.getAttribute("style")),hrefNormalized:"/a"===Y.getAttribute("href"),opacity:/^0.5/.test(Y.style.opacity),cssFloat:!!Y.style.cssFloat,checkOn:"on"===I.value,optSelected:ya.selected,getSetAttribute:"t"!==x.className,enctype:!!o.createElement("form").enctype,html5Clone:"<:nav></:nav>"!==o.createElement("nav").cloneNode(!0).outerHTML,boxModel:"CSS1Compat"===o.compatMode,submitBubbles:!0,
changeBubbles:!0,focusinBubbles:!1,deleteExpando:!0,noCloneEvent:!0,inlineBlockNeedsLayout:!1,shrinkWrapBlocks:!1,reliableMarginRight:!0,boxSizingReliable:!0,pixelPosition:!1};I.checked=!0;E.noCloneChecked=I.cloneNode(!0).checked;xa.disabled=!0;E.optDisabled=!ya.disabled;try{delete x.test}catch(Md){E.deleteExpando=!1}!x.addEventListener&&(x.attachEvent&&x.fireEvent)&&(x.attachEvent("onclick",Gb=function(){E.noCloneEvent=!1}),x.cloneNode(!0).fireEvent("onclick"),x.detachEvent("onclick",Gb));I=o.createElement("input");
I.value="t";I.setAttribute("type","radio");E.radioValue="t"===I.value;I.setAttribute("checked","checked");I.setAttribute("name","t");x.appendChild(I);Z=o.createDocumentFragment();Z.appendChild(x.lastChild);E.checkClone=Z.cloneNode(!0).cloneNode(!0).lastChild.checked;E.appendChecked=I.checked;Z.removeChild(I);Z.appendChild(x);if(x.attachEvent)for(Ta in{submit:!0,change:!0,focusin:!0})za="on"+Ta,fa=za in x,fa||(x.setAttribute(za,"return;"),fa="function"===typeof x[za]),E[Ta+"Bubbles"]=fa;c(function(){var a,
b,d,c=o.getElementsByTagName("body")[0];if(c){a=o.createElement("div");a.style.cssText="visibility:hidden;border:0;width:0;height:0;position:static;top:0;margin-top:1px";c.insertBefore(a,c.firstChild);b=o.createElement("div");a.appendChild(b);b.innerHTML="<table><tr><td></td><td>t</td></tr></table>";d=b.getElementsByTagName("td");d[0].style.cssText="padding:0;margin:0;border:0;display:none";fa=d[0].offsetHeight===0;d[0].style.display="";d[1].style.display="none";E.reliableHiddenOffsets=fa&&d[0].offsetHeight===
0;b.innerHTML="";b.style.cssText="box-sizing:border-box;-moz-box-sizing:border-box;-webkit-box-sizing:border-box;padding:1px;border:1px;display:block;width:4px;margin-top:1%;position:absolute;top:1%;";E.boxSizing=b.offsetWidth===4;E.doesNotIncludeMarginInBodyOffset=c.offsetTop!==1;if(l.getComputedStyle){E.pixelPosition=(l.getComputedStyle(b,null)||{}).top!=="1%";E.boxSizingReliable=(l.getComputedStyle(b,null)||{width:"4px"}).width==="4px";d=o.createElement("div");d.style.cssText=b.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;";
d.style.marginRight=d.style.width="0";b.style.width="1px";b.appendChild(d);E.reliableMarginRight=!parseFloat((l.getComputedStyle(d,null)||{}).marginRight)}if(typeof b.style.zoom!=="undefined"){b.innerHTML="";b.style.cssText="padding:0;margin:0;border:0;display:block;overflow:hidden;width:1px;padding:1px;display:inline;zoom:1";E.inlineBlockNeedsLayout=b.offsetWidth===3;b.style.display="block";b.style.overflow="visible";b.innerHTML="<div></div>";b.firstChild.style.width="5px";E.shrinkWrapBlocks=b.offsetWidth!==
3;a.style.zoom=1}c.removeChild(a)}});Z.removeChild(x);wa=Y=xa=ya=I=Z=x=null;Sa=E}Kc.support=Sa;var qc=/(?:\{[\s\S]*\}|\[[\s\S]*\])$/,pc=/([A-Z])/g;c.extend({cache:{},deletedIds:[],uuid:0,expando:"jQuery"+(c.fn.jquery+Math.random()).replace(/\D/g,""),noData:{embed:!0,object:"clsid:D27CDB6E-AE6D-11cf-96B8-444553540000",applet:!0},hasData:function(a){a=a.nodeType?c.cache[a[c.expando]]:a[c.expando];return!!a&&!p(a)},data:function(a,b,d,e){if(c.acceptData(a)){var f=c.expando,g="string"===typeof b,h=a.nodeType,
i=h?c.cache:a,j=h?a[f]:a[f]&&f;if(j&&i[j]&&(e||i[j].data)||!(g&&d===k)){j||(h?a[f]=j=c.deletedIds.pop()||c.guid++:j=f);i[j]||(i[j]={},h||(i[j].toJSON=c.noop));if("object"===typeof b||"function"===typeof b)e?i[j]=c.extend(i[j],b):i[j].data=c.extend(i[j].data,b);a=i[j];e||(a.data||(a.data={}),a=a.data);d!==k&&(a[c.camelCase(b)]=d);g?(d=a[b],null==d&&(d=a[c.camelCase(b)])):d=a;return d}}},removeData:function(a,b,d){if(c.acceptData(a)){var e,f,g,h=a.nodeType,i=h?c.cache:a,j=h?a[c.expando]:c.expando;if(i[j]){if(b&&
(e=d?i[j]:i[j].data)){c.isArray(b)||(b in e?b=[b]:(b=c.camelCase(b),b=b in e?[b]:b.split(" ")));f=0;for(g=b.length;f<g;f++)delete e[b[f]];if(!(d?p:c.isEmptyObject)(e))return}if(!d&&(delete i[j].data,!p(i[j])))return;h?c.cleanData([a],!0):c.support.deleteExpando||i!=i.window?delete i[j]:i[j]=null}}},_data:function(a,b,d){return c.data(a,b,d,!0)},acceptData:function(a){var b=a.nodeName&&c.noData[a.nodeName.toLowerCase()];return!b||!0!==b&&a.getAttribute("classid")===b}});c.fn.extend({data:function(a,
b){var d,e,f,g,h,i=this[0],j=0,m=null;if(a===k){if(this.length&&(m=c.data(i),1===i.nodeType&&!c._data(i,"parsedAttrs"))){f=i.attributes;for(h=f.length;j<h;j++)g=f[j].name,g.indexOf("data-")||(g=c.camelCase(g.substring(5)),A(i,g,m[g]));c._data(i,"parsedAttrs",!0)}return m}if("object"===typeof a)return this.each(function(){c.data(this,a)});d=a.split(".",2);d[1]=d[1]?"."+d[1]:"";e=d[1]+"!";return c.access(this,function(b){if(b===k)return m=this.triggerHandler("getData"+e,[d[0]]),m===k&&i&&(m=c.data(i,
a),m=A(i,a,m)),m===k&&d[1]?this.data(d[0]):m;d[1]=b;this.each(function(){var f=c(this);f.triggerHandler("setData"+e,d);c.data(this,a,b);f.triggerHandler("changeData"+e,d)})},null,b,1<arguments.length,null,!1)},removeData:function(a){return this.each(function(){c.removeData(this,a)})}});c.extend({queue:function(a,b,d){var e;if(a)return b=(b||"fx")+"queue",e=c._data(a,b),d&&(!e||c.isArray(d)?e=c._data(a,b,c.makeArray(d)):e.push(d)),e||[]},dequeue:function(a,b){var b=b||"fx",d=c.queue(a,b),e=d.length,
f=d.shift(),g=c._queueHooks(a,b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return c._data(a,d)||c._data(a,d,{empty:c.Callbacks("once memory").add(function(){c.removeData(a,b+"queue",!0);c.removeData(a,d,!0)})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):b===
k?this:this.each(function(){var d=c.queue(this,a,b);c._queueHooks(this,a);a==="fx"&&d[0]!=="inprogress"&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},delay:function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,c){var f=setTimeout(b,a);c.stop=function(){clearTimeout(f)}})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,i=function(){--e||f.resolveWith(g,[g])};
"string"!==typeof a&&(b=a,a=k);for(a=a||"fx";h--;)if((d=c._data(g[h],a+"queueHooks"))&&d.empty)e++,d.empty.add(i);i();return f.promise(b)}});var S,Hb,Ib,Jb=/[\t\r\n]/g,Lc=/\r/g,Mc=/^(?:button|input)$/i,Nc=/^(?:button|input|object|select|textarea)$/i,Oc=/^a(?:rea|)$/i,Kb=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,Lb=c.support.getSetAttribute;c.fn.extend({attr:function(a,b){return c.access(this,c.attr,a,b,1<arguments.length)},
removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})},prop:function(a,b){return c.access(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){a=c.propFix[a]||a;return this.each(function(){try{this[a]=k,delete this[a]}catch(b){}})},addClass:function(a){var b,d,e,f,g,h,i;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,this.className))});if(a&&"string"===typeof a){b=a.split(X);d=0;for(e=this.length;d<e;d++)if(f=this[d],1===f.nodeType)if(!f.className&&
1===b.length)f.className=a;else{g=" "+f.className+" ";h=0;for(i=b.length;h<i;h++)0>g.indexOf(" "+b[h]+" ")&&(g+=b[h]+" ");f.className=c.trim(g)}}return this},removeClass:function(a){var b,d,e,f,g,h,i;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,this.className))});if(a&&"string"===typeof a||a===k){b=(a||"").split(X);h=0;for(i=this.length;h<i;h++)if(e=this[h],1===e.nodeType&&e.className){d=(" "+e.className+" ").replace(Jb," ");f=0;for(g=b.length;f<g;f++)for(;0<=
d.indexOf(" "+b[f]+" ");)d=d.replace(" "+b[f]+" "," ");e.className=a?c.trim(d):""}}return this},toggleClass:function(a,b){var d=typeof a,e="boolean"===typeof b;return c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,this.className,b),b)}):this.each(function(){if("string"===d)for(var f,g=0,h=c(this),i=b,j=a.split(X);f=j[g++];)i=e?i:!h.hasClass(f),h[i?"addClass":"removeClass"](f);else if("undefined"===d||"boolean"===d)this.className&&c._data(this,"__className__",this.className),
this.className=this.className||!1===a?"":c._data(this,"__className__")||""})},hasClass:function(a){for(var a=" "+a+" ",b=0,d=this.length;b<d;b++)if(1===this[b].nodeType&&0<=(" "+this[b].className+" ").replace(Jb," ").indexOf(a))return!0;return!1},val:function(a){var b,d,e,f=this[0];if(arguments.length)return e=c.isFunction(a),this.each(function(d){var f=c(this);if(1===this.nodeType&&(d=e?a.call(this,d,f.val()):a,null==d?d="":"number"===typeof d?d+="":c.isArray(d)&&(d=c.map(d,function(a){return a==
null?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],!b||!("set"in b)||b.set(this,d,"value")===k))this.value=d});if(f){if((b=c.valHooks[f.type]||c.valHooks[f.nodeName.toLowerCase()])&&"get"in b&&(d=b.get(f,"value"))!==k)return d;d=f.value;return"string"===typeof d?d.replace(Lc,""):null==d?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=a.attributes.value;return!b||b.specified?a.value:a.text}},select:{get:function(a){var b,d,e=a.selectedIndex,f=[],g=a.options,
h="select-one"===a.type;if(0>e)return null;a=h?e:0;for(d=h?e+1:g.length;a<d;a++)if(b=g[a],b.selected&&(c.support.optDisabled?!b.disabled:null===b.getAttribute("disabled"))&&(!b.parentNode.disabled||!c.nodeName(b.parentNode,"optgroup"))){b=c(b).val();if(h)return b;f.push(b)}return h&&!f.length&&g.length?c(g[e]).val():f},set:function(a,b){var d=c.makeArray(b);c(a).find("option").each(function(){this.selected=0<=c.inArray(c(this).val(),d)});d.length||(a.selectedIndex=-1);return d}}},attrFn:{},attr:function(a,
b,d,e){var f,g,h=a.nodeType;if(a&&!(3===h||8===h||2===h)){if(e&&c.isFunction(c.fn[b]))return c(a)[b](d);if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);if(e=1!==h||!c.isXMLDoc(a))b=b.toLowerCase(),g=c.attrHooks[b]||(Kb.test(b)?Hb:S);if(d!==k)if(null===d)c.removeAttr(a,b);else{if(g&&"set"in g&&e&&(f=g.set(a,d,b))!==k)return f;a.setAttribute(b,d+"");return d}else{if(g&&"get"in g&&e&&null!==(f=g.get(a,b)))return f;f=a.getAttribute(b);return null===f?k:f}}},removeAttr:function(a,b){var d,
e,f,g,h=0;if(b&&1===a.nodeType)for(e=b.split(X);h<e.length;h++)if(f=e[h])d=c.propFix[f]||f,(g=Kb.test(f))||c.attr(a,f,""),a.removeAttribute(Lb?f:d),g&&d in a&&(a[d]=!1)},attrHooks:{type:{set:function(a,b){if(Mc.test(a.nodeName)&&a.parentNode)c.error("type property can't be changed");else if(!c.support.radioValue&&"radio"===b&&c.nodeName(a,"input")){var d=a.value;a.setAttribute("type",b);d&&(a.value=d);return b}}},value:{get:function(a,b){return S&&c.nodeName(a,"button")?S.get(a,b):b in a?a.value:
null},set:function(a,b,d){if(S&&c.nodeName(a,"button"))return S.set(a,b,d);a.value=b}}},propFix:{tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},prop:function(a,b,d){var e,f,g;g=a.nodeType;if(a&&!(3===g||8===g||2===g)){if(g=1!==g||!c.isXMLDoc(a))b=c.propFix[b]||b,f=c.propHooks[b];return d!==
k?f&&"set"in f&&(e=f.set(a,d,b))!==k?e:a[b]=d:f&&"get"in f&&null!==(e=f.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=a.getAttributeNode("tabindex");return b&&b.specified?parseInt(b.value,10):Nc.test(a.nodeName)||Oc.test(a.nodeName)&&a.href?0:k}}}});Hb={get:function(a,b){var d,e=c.prop(a,b);return!0===e||"boolean"!==typeof e&&(d=a.getAttributeNode(b))&&!1!==d.nodeValue?b.toLowerCase():k},set:function(a,b,d){!1===b?c.removeAttr(a,d):(b=c.propFix[d]||d,b in a&&(a[b]=!0),a.setAttribute(d,
d.toLowerCase()));return d}};Lb||(Ib={name:!0,id:!0,coords:!0},S=c.valHooks.button={get:function(a,b){var d;return(d=a.getAttributeNode(b))&&(Ib[b]?""!==d.value:d.specified)?d.value:k},set:function(a,b,d){var c=a.getAttributeNode(d);c||(c=o.createAttribute(d),a.setAttributeNode(c));return c.value=b+""}},c.each(["width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{set:function(a,c){if(""===c)return a.setAttribute(b,"auto"),c}})}),c.attrHooks.contenteditable={get:S.get,set:function(a,
b,d){""===b&&(b="false");S.set(a,b,d)}});c.support.hrefNormalized||c.each(["href","src","width","height"],function(a,b){c.attrHooks[b]=c.extend(c.attrHooks[b],{get:function(a){a=a.getAttribute(b,2);return a===null?k:a}})});c.support.style||(c.attrHooks.style={get:function(a){return a.style.cssText.toLowerCase()||k},set:function(a,b){return a.style.cssText=b+""}});c.support.optSelected||(c.propHooks.selected=c.extend(c.propHooks.selected,{get:function(a){if(a=a.parentNode){a.selectedIndex;a.parentNode&&
a.parentNode.selectedIndex}return null}}));c.support.enctype||(c.propFix.enctype="encoding");c.support.checkOn||c.each(["radio","checkbox"],function(){c.valHooks[this]={get:function(a){return a.getAttribute("value")===null?"on":a.value}}});c.each(["radio","checkbox"],function(){c.valHooks[this]=c.extend(c.valHooks[this],{set:function(a,b){if(c.isArray(b))return a.checked=c.inArray(c(a).val(),b)>=0}})});var Ua=/^(?:textarea|input|select)$/i,Mb=/^([^\.]*|)(?:\.(.+)|)$/,Pc=/(?:^|\s)hover(\.\S+|)\b/,
Qc=/^key/,Rc=/^(?:mouse|contextmenu)|click/,Nb=/^(?:focusinfocus|focusoutblur)$/,Ob=function(a){return c.event.special.hover?a:a.replace(Pc,"mouseenter$1 mouseleave$1")};c.event={add:function(a,b,d,e,f){var g,h,i,j,m,q,n,l,o;if(!(a.nodeType===3||a.nodeType===8||!b||!d||!(g=c._data(a)))){if(d.handler){n=d;d=n.handler;f=n.selector}if(!d.guid)d.guid=c.guid++;i=g.events;if(!i)g.events=i={};h=g.handle;if(!h){g.handle=h=function(a){return typeof c!=="undefined"&&(!a||c.event.triggered!==a.type)?c.event.dispatch.apply(h.elem,
arguments):k};h.elem=a}b=c.trim(Ob(b)).split(" ");for(g=0;g<b.length;g++){j=Mb.exec(b[g])||[];m=j[1];q=(j[2]||"").split(".").sort();o=c.event.special[m]||{};m=(f?o.delegateType:o.bindType)||m;o=c.event.special[m]||{};j=c.extend({type:m,origType:j[1],data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:q.join(".")},n);l=i[m];if(!l){l=i[m]=[];l.delegateCount=0;if(!o.setup||o.setup.call(a,e,q,h)===false)a.addEventListener?a.addEventListener(m,h,false):a.attachEvent&&
a.attachEvent("on"+m,h)}if(o.add){o.add.call(a,j);if(!j.handler.guid)j.handler.guid=d.guid}f?l.splice(l.delegateCount++,0,j):l.push(j);c.event.global[m]=true}a=null}},global:{},remove:function(a,b,d,e,f){var g,h,i,j,m,k,n,l,o,r,p=c.hasData(a)&&c._data(a);if(p&&(n=p.events)){b=c.trim(Ob(b||"")).split(" ");for(g=0;g<b.length;g++){h=Mb.exec(b[g])||[];i=j=h[1];h=h[2];if(i){l=c.event.special[i]||{};i=(e?l.delegateType:l.bindType)||i;o=n[i]||[];m=o.length;h=h?RegExp("(^|\\.)"+h.split(".").sort().join("\\.(?:.*\\.|)")+
"(\\.|$)"):null;for(k=0;k<o.length;k++){r=o[k];if((f||j===r.origType)&&(!d||d.guid===r.guid)&&(!h||h.test(r.namespace))&&(!e||e===r.selector||e==="**"&&r.selector)){o.splice(k--,1);r.selector&&o.delegateCount--;l.remove&&l.remove.call(a,r)}}if(o.length===0&&m!==o.length){(!l.teardown||l.teardown.call(a,h,p.handle)===false)&&c.removeEvent(a,i,p.handle);delete n[i]}}else for(i in n)c.event.remove(a,i+b[g],d,e,true)}if(c.isEmptyObject(n)){delete p.handle;c.removeData(a,"events",true)}}},customEvent:{getData:!0,
setData:!0,changeData:!0},trigger:function(a,b,d,e){if(!d||!(d.nodeType===3||d.nodeType===8)){var f,g,h,i,j,m,q=a.type||a;h=[];if(!Nb.test(q+c.event.triggered)){if(q.indexOf("!")>=0){q=q.slice(0,-1);f=true}if(q.indexOf(".")>=0){h=q.split(".");q=h.shift();h.sort()}if(d&&!c.event.customEvent[q]||c.event.global[q]){a=typeof a==="object"?a[c.expando]?a:new c.Event(q,a):new c.Event(q);a.type=q;a.isTrigger=true;a.exclusive=f;a.namespace=h.join(".");a.namespace_re=a.namespace?RegExp("(^|\\.)"+h.join("\\.(?:.*\\.|)")+
"(\\.|$)"):null;h=q.indexOf(":")<0?"on"+q:"";if(d){a.result=k;if(!a.target)a.target=d;b=b!=null?c.makeArray(b):[];b.unshift(a);i=c.event.special[q]||{};if(!(i.trigger&&i.trigger.apply(d,b)===false)){m=[[d,i.bindType||q]];if(!e&&!i.noBubble&&!c.isWindow(d)){j=i.delegateType||q;f=Nb.test(j+q)?d:d.parentNode;for(g=d;f;f=f.parentNode){m.push([f,j]);g=f}if(g===(d.ownerDocument||o))m.push([g.defaultView||g.parentWindow||l,j])}for(g=0;g<m.length&&!a.isPropagationStopped();g++){f=m[g][0];a.type=m[g][1];(j=
(c._data(f,"events")||{})[a.type]&&c._data(f,"handle"))&&j.apply(f,b);(j=h&&f[h])&&(c.acceptData(f)&&j.apply&&j.apply(f,b)===false)&&a.preventDefault()}a.type=q;if(!e&&!a.isDefaultPrevented()&&(!i._default||i._default.apply(d.ownerDocument,b)===false)&&!(q==="click"&&c.nodeName(d,"a"))&&c.acceptData(d))if(h&&d[q]&&(q!=="focus"&&q!=="blur"||a.target.offsetWidth!==0)&&!c.isWindow(d)){(g=d[h])&&(d[h]=null);c.event.triggered=q;d[q]();c.event.triggered=k;g&&(d[h]=g)}return a.result}}else{d=c.cache;for(g in d)d[g].events&&
d[g].events[q]&&c.event.trigger(a,b,d[g].handle.elem,true)}}}}},dispatch:function(a){var a=c.event.fix(a||l.event),b,d,e,f,g,h,i=(c._data(this,"events")||{})[a.type]||[],j=i.delegateCount,m=Q.call(arguments),q=!a.exclusive&&!a.namespace,n=c.event.special[a.type]||{},o=[];m[0]=a;a.delegateTarget=this;if(!(n.preDispatch&&n.preDispatch.call(this,a)===false)){if(j&&!(a.button&&a.type==="click"))for(d=a.target;d!=this;d=d.parentNode||this)if(d.disabled!==true||a.type!=="click"){f={};g=[];for(b=0;b<j;b++){e=
i[b];h=e.selector;f[h]===k&&(f[h]=e.needsContext?c(h,this).index(d)>=0:c.find(h,this,null,[d]).length);f[h]&&g.push(e)}g.length&&o.push({elem:d,matches:g})}i.length>j&&o.push({elem:this,matches:i.slice(j)});for(b=0;b<o.length&&!a.isPropagationStopped();b++){f=o[b];a.currentTarget=f.elem;for(d=0;d<f.matches.length&&!a.isImmediatePropagationStopped();d++){e=f.matches[d];if(q||!a.namespace&&!e.namespace||a.namespace_re&&a.namespace_re.test(e.namespace)){a.data=e.data;a.handleObj=e;e=((c.event.special[e.origType]||
{}).handle||e.handler).apply(f.elem,m);if(e!==k){a.result=e;if(e===false){a.preventDefault();a.stopPropagation()}}}}}n.postDispatch&&n.postDispatch.call(this,a);return a.result}},props:"attrChange attrName relatedNode srcElement altKey bubbles cancelable ctrlKey currentTarget eventPhase metaKey relatedTarget shiftKey target timeStamp view which".split(" "),fixHooks:{},keyHooks:{props:["char","charCode","key","keyCode"],filter:function(a,b){if(a.which==null)a.which=b.charCode!=null?b.charCode:b.keyCode;
return a}},mouseHooks:{props:"button buttons clientX clientY fromElement offsetX offsetY pageX pageY screenX screenY toElement".split(" "),filter:function(a,b){var d,c,f=b.button,g=b.fromElement;if(a.pageX==null&&b.clientX!=null){d=a.target.ownerDocument||o;c=d.documentElement;d=d.body;a.pageX=b.clientX+(c&&c.scrollLeft||d&&d.scrollLeft||0)-(c&&c.clientLeft||d&&d.clientLeft||0);a.pageY=b.clientY+(c&&c.scrollTop||d&&d.scrollTop||0)-(c&&c.clientTop||d&&d.clientTop||0)}if(!a.relatedTarget&&g)a.relatedTarget=
g===a.target?b.toElement:g;if(!a.which&&f!==k)a.which=f&1?1:f&2?3:f&4?2:0;return a}},fix:function(a){if(a[c.expando])return a;var b,d,e=a,f=c.event.fixHooks[a.type]||{},g=f.props?this.props.concat(f.props):this.props,a=c.Event(e);for(b=g.length;b;){d=g[--b];a[d]=e[d]}if(!a.target)a.target=e.srcElement||o;if(a.target.nodeType===3)a.target=a.target.parentNode;a.metaKey=!!a.metaKey;return f.filter?f.filter(a,e):a},special:{load:{noBubble:!0},focus:{delegateType:"focusin"},blur:{delegateType:"focusout"},
beforeunload:{setup:function(a,b,d){if(c.isWindow(this))this.onbeforeunload=d},teardown:function(a,b){if(this.onbeforeunload===b)this.onbeforeunload=null}}},simulate:function(a,b,d,e){a=c.extend(new c.Event,d,{type:a,isSimulated:true,originalEvent:{}});e?c.event.trigger(a,null,b):c.event.dispatch.call(b,a);a.isDefaultPrevented()&&d.preventDefault()}};c.event.handle=c.event.dispatch;c.removeEvent=o.removeEventListener?function(a,b,d){a.removeEventListener&&a.removeEventListener(b,d,false)}:function(a,
b,d){b="on"+b;if(a.detachEvent){typeof a[b]==="undefined"&&(a[b]=null);a.detachEvent(b,d)}};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);if(a&&a.type){this.originalEvent=a;this.type=a.type;this.isDefaultPrevented=a.defaultPrevented||a.returnValue===false||a.getPreventDefault&&a.getPreventDefault()?r:v}else this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=true};c.Event.prototype={preventDefault:function(){this.isDefaultPrevented=
r;var a=this.originalEvent;if(a)a.preventDefault?a.preventDefault():a.returnValue=false},stopPropagation:function(){this.isPropagationStopped=r;var a=this.originalEvent;if(a){a.stopPropagation&&a.stopPropagation();a.cancelBubble=true}},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=r;this.stopPropagation()},isDefaultPrevented:v,isPropagationStopped:v,isImmediatePropagationStopped:v};c.each({mouseenter:"mouseover",mouseleave:"mouseout"},function(a,b){c.event.special[a]={delegateType:b,
bindType:b,handle:function(a){var e,f=a.relatedTarget,g=a.handleObj;if(!f||f!==this&&!c.contains(this,f)){a.type=g.origType;e=g.handler.apply(this,arguments);a.type=b}return e}}});c.support.submitBubbles||(c.event.special.submit={setup:function(){if(c.nodeName(this,"form"))return false;c.event.add(this,"click._submit keypress._submit",function(a){a=a.target;if((a=c.nodeName(a,"input")||c.nodeName(a,"button")?a.form:k)&&!c._data(a,"_submit_attached")){c.event.add(a,"submit._submit",function(a){a._submit_bubble=
true});c._data(a,"_submit_attached",true)}})},postDispatch:function(a){if(a._submit_bubble){delete a._submit_bubble;this.parentNode&&!a.isTrigger&&c.event.simulate("submit",this.parentNode,a,true)}},teardown:function(){if(c.nodeName(this,"form"))return false;c.event.remove(this,"._submit")}});c.support.changeBubbles||(c.event.special.change={setup:function(){if(Ua.test(this.nodeName)){if(this.type==="checkbox"||this.type==="radio"){c.event.add(this,"propertychange._change",function(a){if(a.originalEvent.propertyName===
"checked")this._just_changed=true});c.event.add(this,"click._change",function(a){if(this._just_changed&&!a.isTrigger)this._just_changed=false;c.event.simulate("change",this,a,true)})}return false}c.event.add(this,"beforeactivate._change",function(a){a=a.target;if(Ua.test(a.nodeName)&&!c._data(a,"_change_attached")){c.event.add(a,"change._change",function(a){this.parentNode&&(!a.isSimulated&&!a.isTrigger)&&c.event.simulate("change",this.parentNode,a,true)});c._data(a,"_change_attached",true)}})},handle:function(a){var b=
a.target;if(this!==b||a.isSimulated||a.isTrigger||b.type!=="radio"&&b.type!=="checkbox")return a.handleObj.handler.apply(this,arguments)},teardown:function(){c.event.remove(this,"._change");return!Ua.test(this.nodeName)}});c.support.focusinBubbles||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=0,e=function(a){c.event.simulate(b,a.target,c.event.fix(a),true)};c.event.special[b]={setup:function(){d++===0&&o.addEventListener(a,e,true)},teardown:function(){--d===0&&o.removeEventListener(a,
e,true)}}});c.fn.extend({on:function(a,b,d,e,f){var g,h;if(typeof a==="object"){if(typeof b!=="string"){d=d||b;b=k}for(h in a)this.on(h,b,d,a[h],f);return this}if(d==null&&e==null){e=b;d=b=k}else if(e==null)if(typeof b==="string"){e=d;d=k}else{e=d;d=b;b=k}if(e===false)e=v;else if(!e)return this;if(f===1){g=e;e=function(a){c().off(a);return g.apply(this,arguments)};e.guid=g.guid||(g.guid=c.guid++)}return this.each(function(){c.event.add(this,a,e,d,b)})},one:function(a,b,d,c){return this.on(a,b,d,c,
1)},off:function(a,b,d){var e;if(a&&a.preventDefault&&a.handleObj){e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if(typeof a==="object"){for(e in a)this.off(e,b,a[e]);return this}if(b===false||typeof b==="function"){d=b;b=k}d===false&&(d=v);return this.each(function(){c.event.remove(this,a,d,b)})},bind:function(a,b,d){return this.on(a,null,b,d)},unbind:function(a,b){return this.off(a,null,b)},live:function(a,b,d){c(this.context).on(a,
this.selector,b,d);return this},die:function(a,b){c(this.context).off(a,this.selector||"**",b);return this},delegate:function(a,b,d,c){return this.on(b,a,d,c)},undelegate:function(a,b,d){return arguments.length===1?this.off(a,"**"):this.off(b,a||"**",d)},trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){if(this[0])return c.event.trigger(a,b,this[0],true)},toggle:function(a){var b=arguments,d=a.guid||c.guid++,e=0,f=function(d){var f=(c._data(this,
"lastToggle"+a.guid)||0)%e;c._data(this,"lastToggle"+a.guid,f+1);d.preventDefault();return b[f].apply(this,arguments)||false};for(f.guid=d;e<b.length;)b[e++].guid=d;return this.click(f)},hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});c.each("blur focus focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup error contextmenu".split(" "),function(a,b){c.fn[b]=function(a,
c){if(c==null){c=a;a=null}return arguments.length>0?this.on(b,null,a,c):this.trigger(b)};if(Qc.test(b))c.event.fixHooks[b]=c.event.keyHooks;if(Rc.test(b))c.event.fixHooks[b]=c.event.mouseHooks});var Sc=l,u=function(a,b,d,c){var d=d||[],b=b||M,f,g,h,i,j=b.nodeType;if(!a||typeof a!=="string")return d;if(j!==1&&j!==9)return[];h=Aa(b);if(!h&&!c&&(f=Tc.exec(a)))if(i=f[1])if(j===9)if((g=b.getElementById(i))&&g.parentNode){if(g.id===i){d.push(g);return d}}else return d;else{if(b.ownerDocument&&(g=b.ownerDocument.getElementById(i))&&
Pb(b,g)&&g.id===i){d.push(g);return d}}else{if(f[2]){ga.apply(d,ha.call(b.getElementsByTagName(a),0));return d}if((i=f[3])&&Qb&&b.getElementsByClassName){ga.apply(d,ha.call(b.getElementsByClassName(i),0));return d}}return Va(a.replace(Ba,"$1"),b,d,c,h)},la=function(a){return function(b){return b.nodeName.toLowerCase()==="input"&&b.type===a}},Rb=function(a){return function(b){var d=b.nodeName.toLowerCase();return(d==="input"||d==="button")&&b.type===a}},aa=function(a){return N(function(b){b=+b;return N(function(d,
c){for(var f,g=a([],d.length,b),h=g.length;h--;)if(d[f=g[h]])d[f]=!(c[f]=d[f])})})},Ca=function(a,b,d){if(a===b)return d;for(a=a.nextSibling;a;){if(a===b)return-1;a=a.nextSibling}return 1},Ea=function(a,b){var d,c,f,g,h,i,j;if(h=Sb[C][a])return b?0:h.slice(0);h=a;i=[];for(j=t.preFilter;h;){if(!d||(c=Uc.exec(h))){c&&(h=h.slice(c[0].length));i.push(f=[])}d=false;if(c=Vc.exec(h)){f.push(d=new Tb(c.shift()));h=h.slice(d.length);d.type=c[0].replace(Ba," ")}for(g in t.filter)if((c=Da[g].exec(h))&&(!j[g]||
(c=j[g](c,M,true)))){f.push(d=new Tb(c.shift()));h=h.slice(d.length);d.type=g;d.matches=c}if(!d)break}return b?h.length:h?u.error(a):Sb(a,i).slice(0)},Xa=function(a,b,d){var c=b.dir,f=d&&b.dir==="parentNode",g=Wc++;return b.first?function(b,d,g){for(;b=b[c];)if(f||b.nodeType===1)return a(b,d,g)}:function(b,d,j){if(j)for(;b=b[c];){if((f||b.nodeType===1)&&a(b,d,j))return b}else for(var m,k=ma+" "+g+" ",n=k+Wa;b=b[c];)if(f||b.nodeType===1){if((m=b[C])===n)return b.sizset;if(typeof m==="string"&&m.indexOf(k)===
0){if(b.sizset)return b}else{b[C]=n;if(a(b,d,j)){b.sizset=true;return b}b.sizset=false}}}},Ya=function(a){return a.length>1?function(b,d,c){for(var f=a.length;f--;)if(!a[f](b,d,c))return false;return true}:a[0]},Fa=function(a,b,d,c,f){for(var g,h=[],i=0,j=a.length,m=b!=null;i<j;i++)if(g=a[i])if(!d||d(g,c,f)){h.push(g);m&&b.push(i)}return h},Za=function(a,b,d,c,f,g){c&&!c[C]&&(c=Za(c));f&&!f[C]&&(f=Za(f,g));return N(function(g,i,j,m){if(!g||!f){var k,n,l=[],o=[],r=i.length;if(!(n=g)){n=b||"*";var p=
j.nodeType?[j]:j,s=[];k=0;for(var w=p.length;k<w;k++)u(n,p[k],s,g);n=s}p=a&&(g||!b)?Fa(n,l,a,j,m):n;s=d?f||(g?a:r||c)?[]:i:p;d&&d(p,s,j,m);if(c){n=Fa(s,o);c(n,[],j,m);for(j=n.length;j--;)if(k=n[j])s[o[j]]=!(p[o[j]]=k)}if(g)for(j=a&&s.length;j--;){if(k=s[j])g[l[j]]=!(i[l[j]]=k)}else{s=Fa(s===i?s.splice(r,s.length):s);f?f(null,i,s,m):ga.apply(i,s)}}})},$a=function(a){var b,d,c,f=a.length,g=t.relative[a[0].type];d=g||t.relative[" "];for(var h=g?1:0,i=Xa(function(a){return a===b},d,true),j=Xa(function(a){return Ub.call(b,
a)>-1},d,true),m=[function(a,d,c){return!g&&(c||d!==Ga)||((b=d).nodeType?i(a,d,c):j(a,d,c))}];h<f;h++)if(d=t.relative[a[h].type])m=[Xa(Ya(m),d)];else{d=t.filter[a[h].type].apply(null,a[h].matches);if(d[C]){for(c=++h;c<f;c++)if(t.relative[a[c].type])break;return Za(h>1&&Ya(m),h>1&&a.slice(0,h-1).join("").replace(Ba,"$1"),d,h<c&&$a(a.slice(h,c)),c<f&&$a(a=a.slice(c)),c<f&&a.join(""))}m.push(d)}return Ya(m)},Va=function(a,b,d,c,f){var g,h,i,j,m=Ea(a);if(!c&&m.length===1){h=m[0]=m[0].slice(0);if(h.length>
2&&(i=h[0]).type==="ID"&&b.nodeType===9&&!f&&t.relative[h[1].type]){b=t.find.ID(i.matches[0].replace(ba,""),b,f)[0];if(!b)return d;a=a.slice(h.shift().length)}for(g=Da.POS.test(a)?-1:h.length-1;g>=0;g--){i=h[g];if(t.relative[j=i.type])break;if(j=t.find[j])if(c=j(i.matches[0].replace(ba,""),ab.test(h[0].type)&&b.parentNode||b,f)){h.splice(g,1);a=c.length&&h.join("");if(!a){ga.apply(d,ha.call(c,0));return d}break}}}bb(a,m)(c,b,f,d,ab.test(a));return d},Vb=function(){},Wa,cb,t,Ha,Aa,Pb,bb,db,na,Ga,Wb=
!0,C=("sizcache"+Math.random()).replace(".",""),Tb=String,M=Sc.document,L=M.documentElement,ma=0,Wc=0,Xc=[].pop,ga=[].push,ha=[].slice,Ub=[].indexOf||function(a){for(var b=0,d=this.length;b<d;b++)if(this[b]===a)return b;return-1},N=function(a,b){a[C]=b==null||b;return a},eb=function(){var a={},b=[];return N(function(d,c){b.push(d)>t.cacheLength&&delete a[b.shift()];return a[d]=c},a)},Xb=eb(),Sb=eb(),Yb=eb(),Zb="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+
"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w#")+")|)|)[\\x20\\t\\r\\n\\f]*\\]",fb=":((?:\\\\.|[-\\w]|[^\\x00-\\xa0])+)(?:\\((?:(['\"])((?:\\\\.|[^\\\\])*?)\\2|([^()[\\]]*|(?:(?:"+Zb+")|[^:]|\\\\.)*|.*))\\)|)",Ba=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),Uc=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Vc=/^[\x20\t\r\n\f]*([\x20\t\r\n\f>+~])[\x20\t\r\n\f]*/,Yc=RegExp(fb),Tc=/^(?:#([\w\-]+)|(\w+)|\.([\w\-]+))$/,ab=/[\x20\t\r\n\f]*[+~]/,Zc=/h\d/i,$c=/input|select|textarea|button/i,
ba=/\\(?!\\)/g,Da={ID:/^#((?:\\.|[-\w]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[-\w]|[^\x00-\xa0])+)/,NAME:/^\[name=['"]?((?:\\.|[-\w]|[^\x00-\xa0])+)['"]?\]/,TAG:RegExp("^("+"(?:\\\\.|[-\\w]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+Zb),PSEUDO:RegExp("^"+fb),POS:/:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i,CHILD:RegExp("^:(only|nth|first|last)-child(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},T=function(a){var b=M.createElement("div");try{return a(b)}catch(d){return false}finally{}},ad=T(function(a){a.appendChild(M.createComment(""));return!a.getElementsByTagName("*").length}),bd=T(function(a){a.innerHTML="<a href='#'></a>";return a.firstChild&&typeof a.firstChild.getAttribute!=="undefined"&&a.firstChild.getAttribute("href")===
"#"}),cd=T(function(a){a.innerHTML="<select></select>";a=typeof a.lastChild.getAttribute("multiple");return a!=="boolean"&&a!=="string"}),Qb=T(function(a){a.innerHTML="<div class='hidden e'></div><div class='hidden'></div>";if(!a.getElementsByClassName||!a.getElementsByClassName("e").length)return false;a.lastChild.className="e";return a.getElementsByClassName("e").length===2}),dd=T(function(a){a.id=C+0;a.innerHTML="<a name='"+C+"'></a><div name='"+C+"'></div>";L.insertBefore(a,L.firstChild);var b=
M.getElementsByName&&M.getElementsByName(C).length===2+M.getElementsByName(C+0).length;cb=!M.getElementById(C);L.removeChild(a);return b});try{ha.call(L.childNodes,0)[0].nodeType}catch(Nd){ha=function(a){for(var b,d=[];b=this[a];a++)d.push(b);return d}}u.matches=function(a,b){return u(a,null,null,b)};u.matchesSelector=function(a,b){return u(b,null,null,[a]).length>0};Ha=u.getText=function(a){var b,d="",c=0;if(b=a.nodeType)if(b===1||b===9||b===11){if(typeof a.textContent==="string")return a.textContent;
for(a=a.firstChild;a;a=a.nextSibling)d=d+Ha(a)}else{if(b===3||b===4)return a.nodeValue}else for(;b=a[c];c++)d=d+Ha(b);return d};Aa=u.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?a.nodeName!=="HTML":false};Pb=u.contains=L.contains?function(a,b){var d=a.nodeType===9?a.documentElement:a,c=b&&b.parentNode;return a===c||!(!c||!(c.nodeType===1&&d.contains&&d.contains(c)))}:L.compareDocumentPosition?function(a,b){return b&&!!(a.compareDocumentPosition(b)&16)}:function(a,b){for(;b=
b.parentNode;)if(b===a)return true;return false};u.attr=function(a,b){var d,c=Aa(a);c||(b=b.toLowerCase());if(d=t.attrHandle[b])return d(a);if(c||cd)return a.getAttribute(b);return(d=a.getAttributeNode(b))?typeof a[b]==="boolean"?a[b]?b:null:d.specified?d.value:null:null};t=u.selectors={cacheLength:50,createPseudo:N,match:Da,attrHandle:bd?{}:{href:function(a){return a.getAttribute("href",2)},type:function(a){return a.getAttribute("type")}},find:{ID:cb?function(a,b,d){if(typeof b.getElementById!==
"undefined"&&!d)return(a=b.getElementById(a))&&a.parentNode?[a]:[]}:function(a,b,d){if(typeof b.getElementById!=="undefined"&&!d)return(b=b.getElementById(a))?b.id===a||typeof b.getAttributeNode!=="undefined"&&b.getAttributeNode("id").value===a?[b]:void 0:[]},TAG:ad?function(a,b){if(typeof b.getElementsByTagName!=="undefined")return b.getElementsByTagName(a)}:function(a,b){var d=b.getElementsByTagName(a);if(a==="*"){for(var c,f=[],g=0;c=d[g];g++)c.nodeType===1&&f.push(c);return f}return d},NAME:dd&&
function(a,b){if(typeof b.getElementsByName!=="undefined")return b.getElementsByName(name)},CLASS:Qb&&function(a,b,d){if(typeof b.getElementsByClassName!=="undefined"&&!d)return b.getElementsByClassName(a)}},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(ba,"");a[3]=(a[4]||a[5]||"").replace(ba,"");a[2]==="~="&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=
a[1].toLowerCase();if(a[1]==="nth"){a[2]||u.error(a[0]);a[3]=+(a[3]?a[4]+(a[5]||1):2*(a[2]==="even"||a[2]==="odd"));a[4]=+(a[6]+a[7]||a[2]==="odd")}else a[2]&&u.error(a[0]);return a},PSEUDO:function(a){var b,d;if(Da.CHILD.test(a[0]))return null;if(a[3])a[2]=a[3];else if(b=a[4]){if(Yc.test(b)&&(d=Ea(b,true))&&(d=b.indexOf(")",b.length-d)-b.length)){b=b.slice(0,d);a[0]=a[0].slice(0,d)}a[2]=b}return a.slice(0,3)}},filter:{ID:cb?function(a){a=a.replace(ba,"");return function(b){return b.getAttribute("id")===
a}}:function(a){a=a.replace(ba,"");return function(b){return(b=typeof b.getAttributeNode!=="undefined"&&b.getAttributeNode("id"))&&b.value===a}},TAG:function(a){if(a==="*")return function(){return true};a=a.replace(ba,"").toLowerCase();return function(b){return b.nodeName&&b.nodeName.toLowerCase()===a}},CLASS:function(a){var b=Xb[C][a];b||(b=Xb(a,RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)")));return function(a){return b.test(a.className||typeof a.getAttribute!=="undefined"&&a.getAttribute("class")||
"")}},ATTR:function(a,b,d){return function(c){c=u.attr(c,a);if(c==null)return b==="!=";if(!b)return true;c=c+"";return b==="="?c===d:b==="!="?c!==d:b==="^="?d&&c.indexOf(d)===0:b==="*="?d&&c.indexOf(d)>-1:b==="$="?d&&c.substr(c.length-d.length)===d:b==="~="?(" "+c+" ").indexOf(d)>-1:b==="|="?c===d||c.substr(0,d.length+1)===d+"-":false}},CHILD:function(a,b,d,c){return a==="nth"?function(a){var b,h;b=a.parentNode;if(d===1&&c===0)return true;if(b){h=0;for(b=b.firstChild;b;b=b.nextSibling)if(b.nodeType===
1){h++;if(a===b)break}}h=h-c;return h===d||h%d===0&&h/d>=0}:function(b){var d=b;switch(a){case "only":case "first":for(;d=d.previousSibling;)if(d.nodeType===1)return false;if(a==="first")return true;d=b;case "last":for(;d=d.nextSibling;)if(d.nodeType===1)return false;return true}}},PSEUDO:function(a,b){var d,c=t.pseudos[a]||t.setFilters[a.toLowerCase()]||u.error("unsupported pseudo: "+a);if(c[C])return c(b);if(c.length>1){d=[a,a,"",b];return t.setFilters.hasOwnProperty(a.toLowerCase())?N(function(a,
d){for(var h,i=c(a,b),j=i.length;j--;){h=Ub.call(a,i[j]);a[h]=!(d[h]=i[j])}}):function(a){return c(a,0,d)}}return c}},pseudos:{not:N(function(a){var b=[],d=[],c=bb(a.replace(Ba,"$1"));return c[C]?N(function(a,b,d,i){for(var i=c(a,null,i,[]),j=a.length;j--;)if(d=i[j])a[j]=!(b[j]=d)}):function(a,g,h){b[0]=a;c(b,null,h,d);return!d.pop()}}),has:N(function(a){return function(b){return u(a,b).length>0}}),contains:N(function(a){return function(b){return(b.textContent||b.innerText||Ha(b)).indexOf(a)>-1}}),
enabled:function(a){return a.disabled===false},disabled:function(a){return a.disabled===true},checked:function(a){var b=a.nodeName.toLowerCase();return b==="input"&&!!a.checked||b==="option"&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return a.selected===true},parent:function(a){return!t.pseudos.empty(a)},empty:function(a){for(var b,a=a.firstChild;a;){if(a.nodeName>"@"||(b=a.nodeType)===3||b===4)return false;a=a.nextSibling}return true},header:function(a){return Zc.test(a.nodeName)},
text:function(a){var b,d;return a.nodeName.toLowerCase()==="input"&&(b=a.type)==="text"&&((d=a.getAttribute("type"))==null||d.toLowerCase()===b)},radio:la("radio"),checkbox:la("checkbox"),file:la("file"),password:la("password"),image:la("image"),submit:Rb("submit"),reset:Rb("reset"),button:function(a){var b=a.nodeName.toLowerCase();return b==="input"&&a.type==="button"||b==="button"},input:function(a){return $c.test(a.nodeName)},focus:function(a){var b=a.ownerDocument;return a===b.activeElement&&
(!b.hasFocus||b.hasFocus())&&!(!a.type&&!a.href)},active:function(a){return a===a.ownerDocument.activeElement},first:aa(function(){return[0]}),last:aa(function(a,b){return[b-1]}),eq:aa(function(a,b,d){return[d<0?d+b:d]}),even:aa(function(a,b){for(var d=0;d<b;d=d+2)a.push(d);return a}),odd:aa(function(a,b){for(var d=1;d<b;d=d+2)a.push(d);return a}),lt:aa(function(a,b,d){for(b=d<0?d+b:d;--b>=0;)a.push(b);return a}),gt:aa(function(a,b,d){for(d=d<0?d+b:d;++d<b;)a.push(d);return a})}};db=L.compareDocumentPosition?
function(a,b){if(a===b){na=true;return 0}return(!a.compareDocumentPosition||!b.compareDocumentPosition?a.compareDocumentPosition:a.compareDocumentPosition(b)&4)?-1:1}:function(a,b){if(a===b){na=true;return 0}if(a.sourceIndex&&b.sourceIndex)return a.sourceIndex-b.sourceIndex;var d,c,f=[],g=[];d=a.parentNode;c=b.parentNode;var h=d;if(d===c)return Ca(a,b);if(d){if(!c)return 1}else return-1;for(;h;){f.unshift(h);h=h.parentNode}for(h=c;h;){g.unshift(h);h=h.parentNode}d=f.length;c=g.length;for(h=0;h<d&&
h<c;h++)if(f[h]!==g[h])return Ca(f[h],g[h]);return h===d?Ca(a,g[h],-1):Ca(f[h],b,1)};[0,0].sort(db);Wb=!na;u.uniqueSort=function(a){var b,d=1;na=Wb;a.sort(db);if(na)for(;b=a[d];d++)b===a[d-1]&&a.splice(d--,1);return a};u.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};bb=u.compile=function(a,b){var d,c=[],f=[],g=Yb[C][a];if(!g){b||(b=Ea(a));for(d=b.length;d--;){g=$a(b[d]);g[C]?c.push(g):f.push(g)}var h=c.length>0,i=f.length>0,j=function(a,b,d,g,k){var l,o,r=[],p=0,s="0",
w=a&&[],z=k!=null,y=Ga,x=a||i&&t.find.TAG("*",k&&b.parentNode||b),v=ma=ma+(y==null?1:Math.E);if(z){Ga=b!==M&&b;Wa=j.el}for(;(k=x[s])!=null;s++){if(i&&k){for(l=0;o=f[l];l++)if(o(k,b,d)){g.push(k);break}if(z){ma=v;Wa=++j.el}}if(h){(k=!o&&k)&&p--;a&&w.push(k)}}p=p+s;if(h&&s!==p){for(l=0;o=c[l];l++)o(w,r,b,d);if(a){if(p>0)for(;s--;)!w[s]&&!r[s]&&(r[s]=Xc.call(g));r=Fa(r)}ga.apply(g,r);z&&(!a&&r.length>0&&p+c.length>1)&&u.uniqueSort(g)}if(z){ma=v;Ga=y}return w};j.el=0;d=h?N(j):j;g=Yb(a,d)}return g};if(M.querySelectorAll){var $b,
ed=Va,fd=/'|\\/g,gd=/\=[\x20\t\r\n\f]*([^'"\]]*)[\x20\t\r\n\f]*\]/g,O=[":focus"],Ia=[":active",":focus"],Ja=L.matchesSelector||L.mozMatchesSelector||L.webkitMatchesSelector||L.oMatchesSelector||L.msMatchesSelector;T(function(a){a.innerHTML="<select><option selected=''></option></select>";a.querySelectorAll("[selected]").length||O.push("\\[[\\x20\\t\\r\\n\\f]*(?:checked|disabled|ismap|multiple|readonly|selected|value)");a.querySelectorAll(":checked").length||O.push(":checked")});T(function(a){a.innerHTML=
"<p test=''></p>";a.querySelectorAll("[test^='']").length&&O.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:\"\"|'')");a.innerHTML="<input type='hidden'/>";a.querySelectorAll(":enabled").length||O.push(":enabled",":disabled")});O=RegExp(O.join("|"));Va=function(a,b,d,c,f){if(!c&&!f&&(!O||!O.test(a))){var g,h,i=true,j=C;h=b;g=b.nodeType===9&&a;if(b.nodeType===1&&b.nodeName.toLowerCase()!=="object"){g=Ea(a);(i=b.getAttribute("id"))?j=i.replace(fd,"\\$&"):b.setAttribute("id",j);j="[id='"+j+"'] ";for(h=g.length;h--;)g[h]=
j+g[h].join("");h=ab.test(a)&&b.parentNode||b;g=g.join(",")}if(g)try{ga.apply(d,ha.call(h.querySelectorAll(g),0));return d}catch(m){}finally{i||b.removeAttribute("id")}}return ed(a,b,d,c,f)};Ja&&(T(function(a){$b=Ja.call(a,"div");try{Ja.call(a,"[test!='']:sizzle");Ia.push("!=",fb)}catch(b){}}),Ia=RegExp(Ia.join("|")),u.matchesSelector=function(a,b){b=b.replace(gd,"='$1']");if(!Aa(a)&&!Ia.test(b)&&(!O||!O.test(b)))try{var d=Ja.call(a,b);if(d||$b||a.document&&a.document.nodeType!==11)return d}catch(c){}return u(b,
null,null,[a]).length>0})}t.pseudos.nth=t.pseudos.eq;t.filters=Vb.prototype=t.pseudos;t.setFilters=new Vb;u.attr=c.attr;c.find=u;c.expr=u.selectors;c.expr[":"]=c.expr.pseudos;c.unique=u.uniqueSort;c.text=u.getText;c.isXMLDoc=u.isXML;c.contains=u.contains;var hd=/Until$/,id=/^(?:parents|prev(?:Until|All))/,rc=/^.[^:#\[\.,]*$/,ac=c.expr.match.needsContext,jd={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({find:function(a){var b,d,e,f,g,h,i=this;if(typeof a!=="string")return c(a).filter(function(){b=
0;for(d=i.length;b<d;b++)if(c.contains(i[b],this))return true});h=this.pushStack("","find",a);b=0;for(d=this.length;b<d;b++){e=h.length;c.find(a,this[b],h);if(b>0)for(f=e;f<h.length;f++)for(g=0;g<e;g++)if(h[g]===h[f]){h.splice(f--,1);break}}return h},has:function(a){var b,d=c(a,this),e=d.length;return this.filter(function(){for(b=0;b<e;b++)if(c.contains(this,d[b]))return true})},not:function(a){return this.pushStack(z(this,a,false),"not",a)},filter:function(a){return this.pushStack(z(this,a,true),
"filter",a)},is:function(a){return!!a&&(typeof a==="string"?ac.test(a)?c(a,this.context).index(this[0])>=0:c.filter(a,this).length>0:this.filter(a).length>0)},closest:function(a,b){for(var d,e=0,f=this.length,g=[],h=ac.test(a)||typeof a!=="string"?c(a,b||this.context):0;e<f;e++)for(d=this[e];d&&d.ownerDocument&&d!==b&&d.nodeType!==11;){if(h?h.index(d)>-1:c.find.matchesSelector(d,a)){g.push(d);break}d=d.parentNode}g=g.length>1?c.unique(g):g;return this.pushStack(g,"closest",a)},index:function(a){return!a?
this[0]&&this[0].parentNode?this.prevAll().length:-1:typeof a==="string"?c.inArray(this[0],c(a)):c.inArray(a.jquery?a[0]:a,this)},add:function(a,b){var d=typeof a==="string"?c(a,b):c.makeArray(a&&a.nodeType?[a]:a),e=c.merge(this.get(),d);return this.pushStack(F(d[0])||F(e[0])?e:c.unique(e))},addBack:function(a){return this.add(a==null?this.prevObject:this.prevObject.filter(a))}});c.fn.andSelf=c.fn.addBack;c.each({parent:function(a){return(a=a.parentNode)&&a.nodeType!==11?a:null},parents:function(a){return c.dir(a,
"parentNode")},parentsUntil:function(a,b,d){return c.dir(a,"parentNode",d)},next:function(a){return V(a,"nextSibling")},prev:function(a){return V(a,"previousSibling")},nextAll:function(a){return c.dir(a,"nextSibling")},prevAll:function(a){return c.dir(a,"previousSibling")},nextUntil:function(a,b,d){return c.dir(a,"nextSibling",d)},prevUntil:function(a,b,d){return c.dir(a,"previousSibling",d)},siblings:function(a){return c.sibling((a.parentNode||{}).firstChild,a)},children:function(a){return c.sibling(a.firstChild)},
contents:function(a){return c.nodeName(a,"iframe")?a.contentDocument||a.contentWindow.document:c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);hd.test(a)||(e=d);e&&typeof e==="string"&&(f=c.filter(e,f));f=this.length>1&&!jd[a]?c.unique(f):f;this.length>1&&id.test(a)&&(f=f.reverse());return this.pushStack(f,a,Q.call(arguments).join(","))}});c.extend({filter:function(a,b,d){d&&(a=":not("+a+")");return b.length===1?c.find.matchesSelector(b[0],a)?[b[0]]:[]:c.find.matches(a,
b)},dir:function(a,b,d){for(var e=[],a=a[b];a&&a.nodeType!==9&&(d===k||a.nodeType!==1||!c(a).is(d));){a.nodeType===1&&e.push(a);a=a[b]}return e},sibling:function(a,b){for(var d=[];a;a=a.nextSibling)a.nodeType===1&&a!==b&&d.push(a);return d}});var ob="abbr|article|aside|audio|bdi|canvas|data|datalist|details|figcaption|figure|footer|header|hgroup|mark|meter|nav|output|progress|section|summary|time|video",kd=/ jQuery\d+="(?:null|\d+)"/g,gb=/^\s+/,bc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/gi,
cc=/<([\w:]+)/,ld=/<tbody/i,md=/<|&#?\w+;/,nd=/<(?:script|style|link)/i,od=/<(?:script|object|embed|option|style)/i,hb=RegExp("<(?:"+ob+")[\\s/>]","i"),pb=/^(?:checkbox|radio)$/,dc=/checked\s*(?:[^=]|=\s*.checked.)/i,pd=/\/(java|ecma)script/i,qd=/^\s*<!(?:\[CDATA\[|\-\-)|[\]\-]{2}>\s*$/g,K={option:[1,"<select multiple='multiple'>","</select>"],legend:[1,"<fieldset>","</fieldset>"],thead:[1,"<table>","</table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],
col:[2,"<table><tbody></tbody><colgroup>","</colgroup></table>"],area:[1,"<map>","</map>"],_default:[0,"",""]},ec=B(o),ib=ec.appendChild(o.createElement("div"));K.optgroup=K.option;K.tbody=K.tfoot=K.colgroup=K.caption=K.thead;K.th=K.td;c.support.htmlSerialize||(K._default=[1,"X<div>","</div>"]);c.fn.extend({text:function(a){return c.access(this,function(a){return a===k?c.text(this):this.empty().append((this[0]&&this[0].ownerDocument||o).createTextNode(a))},null,a,arguments.length)},wrapAll:function(a){if(c.isFunction(a))return this.each(function(b){c(this).wrapAll(a.call(this,
b))});if(this[0]){var b=c(a,this[0].ownerDocument).eq(0).clone(true);this[0].parentNode&&b.insertBefore(this[0]);b.map(function(){for(var a=this;a.firstChild&&a.firstChild.nodeType===1;)a=a.firstChild;return a}).append(this)}return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?
a.call(this,d):a)})},unwrap:function(){return this.parent().each(function(){c.nodeName(this,"body")||c(this).replaceWith(this.childNodes)}).end()},append:function(){return this.domManip(arguments,true,function(a){(this.nodeType===1||this.nodeType===11)&&this.appendChild(a)})},prepend:function(){return this.domManip(arguments,true,function(a){(this.nodeType===1||this.nodeType===11)&&this.insertBefore(a,this.firstChild)})},before:function(){if(!F(this[0]))return this.domManip(arguments,false,function(a){this.parentNode.insertBefore(a,
this)});if(arguments.length){var a=c.clean(arguments);return this.pushStack(c.merge(a,this),"before",this.selector)}},after:function(){if(!F(this[0]))return this.domManip(arguments,false,function(a){this.parentNode.insertBefore(a,this.nextSibling)});if(arguments.length){var a=c.clean(arguments);return this.pushStack(c.merge(this,a),"after",this.selector)}},remove:function(a,b){for(var d,e=0;(d=this[e])!=null;e++)if(!a||c.filter(a,[d]).length){if(!b&&d.nodeType===1){c.cleanData(d.getElementsByTagName("*"));
c.cleanData([d])}d.parentNode&&d.parentNode.removeChild(d)}return this},empty:function(){for(var a,b=0;(a=this[b])!=null;b++)for(a.nodeType===1&&c.cleanData(a.getElementsByTagName("*"));a.firstChild;)a.removeChild(a.firstChild);return this},clone:function(a,b){a=a==null?false:a;b=b==null?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return c.access(this,function(a){var d=this[0]||{},e=0,f=this.length;if(a===k)return d.nodeType===1?d.innerHTML.replace(kd,""):k;if(typeof a===
"string"&&!nd.test(a)&&(c.support.htmlSerialize||!hb.test(a))&&(c.support.leadingWhitespace||!gb.test(a))&&!K[(cc.exec(a)||["",""])[1].toLowerCase()]){a=a.replace(bc,"<$1></$2>");try{for(;e<f;e++){d=this[e]||{};if(d.nodeType===1){c.cleanData(d.getElementsByTagName("*"));d.innerHTML=a}}d=0}catch(g){}}d&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(a){if(!F(this[0])){if(c.isFunction(a))return this.each(function(b){var d=c(this),e=d.html();d.replaceWith(a.call(this,b,e))});
typeof a!=="string"&&(a=c(a).detach());return this.each(function(){var b=this.nextSibling,d=this.parentNode;c(this).remove();b?c(b).before(a):c(d).append(a)})}return this.length?this.pushStack(c(c.isFunction(a)?a():a),"replaceWith",a):this},detach:function(a){return this.remove(a,true)},domManip:function(a,b,d){var a=[].concat.apply([],a),e,f,g,h=0,i=a[0],j=[],m=this.length;if(!c.support.checkClone&&m>1&&typeof i==="string"&&dc.test(i))return this.each(function(){c(this).domManip(a,b,d)});if(c.isFunction(i))return this.each(function(e){var f=
c(this);a[0]=i.call(this,e,b?f.html():k);f.domManip(a,b,d)});if(this[0]){e=c.buildFragment(a,this,j);g=e.fragment;f=g.firstChild;g.childNodes.length===1&&(g=f);if(f){b=b&&c.nodeName(f,"tr");for(e=e.cacheable||m-1;h<m;h++)d.call(b&&c.nodeName(this[h],"table")?this[h].getElementsByTagName("tbody")[0]||this[h].appendChild(this[h].ownerDocument.createElement("tbody")):this[h],h===e?g:c.clone(g,true,true))}g=f=null;j.length&&c.each(j,function(a,b){b.src?c.ajax?c.ajax({url:b.src,type:"GET",dataType:"script",
async:false,global:false,"throws":true}):c.error("no ajax"):c.globalEval((b.text||b.textContent||b.innerHTML||"").replace(qd,""));b.parentNode&&b.parentNode.removeChild(b)})}return this}});c.buildFragment=function(a,b,d){var e,f,g,h=a[0],b=b||o,b=!b.nodeType&&b[0]||b,b=b.ownerDocument||b;if(a.length===1&&typeof h==="string"&&h.length<512&&b===o&&h.charAt(0)==="<"&&!od.test(h)&&(c.support.checkClone||!dc.test(h))&&(c.support.html5Clone||!hb.test(h))){f=true;e=c.fragments[h];g=e!==k}if(!e){e=b.createDocumentFragment();
c.clean(a,b,e,d);f&&(c.fragments[h]=g&&e)}return{fragment:e,cacheable:f}};c.fragments={};c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(d){var e,f=0,g=[],d=c(d),h=d.length;e=this.length===1&&this[0].parentNode;if((e==null||e&&e.nodeType===11&&e.childNodes.length===1)&&h===1){d[b](this[0]);return this}for(;f<h;f++){e=(f>0?this.clone(true):this).get();c(d[f])[b](e);g=g.concat(e)}return this.pushStack(g,
a,d.selector)}});c.extend({clone:function(a,b,d){var e,f,g,h;if(c.support.html5Clone||c.isXMLDoc(a)||!hb.test("<"+a.nodeName+">"))h=a.cloneNode(true);else{ib.innerHTML=a.outerHTML;ib.removeChild(h=ib.firstChild)}if((!c.support.noCloneEvent||!c.support.noCloneChecked)&&(a.nodeType===1||a.nodeType===11)&&!c.isXMLDoc(a)){s(a,h);e=D(a);f=D(h);for(g=0;e[g];++g)f[g]&&s(e[g],f[g])}if(b){R(a,h);if(d){e=D(a);f=D(h);for(g=0;e[g];++g)R(e[g],f[g])}}return h},clean:function(a,b,d,e){var f,g,h,i,j,m,k=b===o&&ec,
n=[];if(!b||typeof b.createDocumentFragment==="undefined")b=o;for(f=0;(h=a[f])!=null;f++){typeof h==="number"&&(h=h+"");if(h){if(typeof h==="string")if(md.test(h)){k=k||B(b);m=b.createElement("div");k.appendChild(m);h=h.replace(bc,"<$1></$2>");g=(cc.exec(h)||["",""])[1].toLowerCase();i=K[g]||K._default;j=i[0];for(m.innerHTML=i[1]+h+i[2];j--;)m=m.lastChild;if(!c.support.tbody){j=ld.test(h);i=g==="table"&&!j?m.firstChild&&m.firstChild.childNodes:i[1]==="<table>"&&!j?m.childNodes:[];for(g=i.length-1;g>=
0;--g)c.nodeName(i[g],"tbody")&&!i[g].childNodes.length&&i[g].parentNode.removeChild(i[g])}!c.support.leadingWhitespace&&gb.test(h)&&m.insertBefore(b.createTextNode(gb.exec(h)[0]),m.firstChild);h=m.childNodes;m.parentNode.removeChild(m)}else h=b.createTextNode(h);h.nodeType?n.push(h):c.merge(n,h)}}m&&(h=m=k=null);if(!c.support.appendChecked)for(f=0;(h=n[f])!=null;f++)c.nodeName(h,"input")?mb(h):typeof h.getElementsByTagName!=="undefined"&&c.grep(h.getElementsByTagName("input"),mb);if(d){a=function(a){if(!a.type||
pd.test(a.type))return e?e.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a)};for(f=0;(h=n[f])!=null;f++)if(!c.nodeName(h,"script")||!a(h)){d.appendChild(h);if(typeof h.getElementsByTagName!=="undefined"){h=c.grep(c.merge([],h.getElementsByTagName("script")),a);n.splice.apply(n,[f+1,0].concat(h));f=f+h.length}}}return n},cleanData:function(a,b){for(var d,e,f,g,h=0,i=c.expando,j=c.cache,m=c.support.deleteExpando,k=c.event.special;(f=a[h])!=null;h++)if(b||c.acceptData(f))if(d=(e=f[i])&&
j[e]){if(d.events)for(g in d.events)k[g]?c.event.remove(f,g):c.removeEvent(f,g,d.handle);if(j[e]){delete j[e];m?delete f[i]:f.removeAttribute?f.removeAttribute(i):f[i]=null;c.deletedIds.push(e)}}}});var Ka,U;c.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||/(msie) ([\w.]+)/.exec(a)||a.indexOf("compatible")<0&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};
Ka=c.uaMatch(wc.userAgent);U={};Ka.browser&&(U[Ka.browser]=!0,U.version=Ka.version);U.chrome?U.webkit=!0:U.webkit&&(U.safari=!0);c.browser=U;c.sub=function(){function a(b,c){return new a.fn.init(b,c)}c.extend(true,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=function(d,e){e&&(e instanceof c&&!(e instanceof a))&&(e=a(e));return c.fn.init.call(this,d,e,b)};a.fn.init.prototype=a.fn;var b=a(o);return a};var G,da,ea,jb=/alpha\([^)]*\)/i,rd=/opacity=([^)]*)/,
sd=/^(top|right|bottom|left)$/,td=/^(none|table(?!-c[ea]).+)/,fc=/^margin/,sc=RegExp("^("+ua+")(.*)$","i"),oa=RegExp("^("+ua+")(?!px)[a-z%]+$","i"),ud=RegExp("^([-+])=("+ua+")","i"),Na={},vd={position:"absolute",visibility:"hidden",display:"block"},gc={letterSpacing:0,fontWeight:400},W=["Top","Right","Bottom","Left"],qb=["Webkit","O","Moz","ms"],wd=c.fn.toggle;c.fn.extend({css:function(a,b){return c.access(this,function(a,b,f){return f!==k?c.style(a,b,f):c.css(a,b)},a,b,arguments.length>1)},show:function(){return J(this,
true)},hide:function(){return J(this)},toggle:function(a,b){var d=typeof a==="boolean";return c.isFunction(a)&&c.isFunction(b)?wd.apply(this,arguments):this.each(function(){(d?a:P(this))?c(this).show():c(this).hide()})}});c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var d=G(a,"opacity");return d===""?"1":d}}}},cssNumber:{fillOpacity:!0,fontWeight:!0,lineHeight:!0,opacity:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":c.support.cssFloat?"cssFloat":"styleFloat"},style:function(a,
b,d,e){if(a&&!(a.nodeType===3||a.nodeType===8||!a.style)){var f,g,h,i=c.camelCase(b),j=a.style,b=c.cssProps[i]||(c.cssProps[i]=nb(j,i));h=c.cssHooks[b]||c.cssHooks[i];if(d!==k){g=typeof d;if(g==="string"&&(f=ud.exec(d))){d=(f[1]+1)*f[2]+parseFloat(c.css(a,b));g="number"}if(!(d==null||g==="number"&&isNaN(d))){g==="number"&&!c.cssNumber[i]&&(d=d+"px");if(!h||!("set"in h)||(d=h.set(a,d,e))!==k)try{j[b]=d}catch(m){}}}else return h&&"get"in h&&(f=h.get(a,false,e))!==k?f:j[b]}},css:function(a,b,d,e){var f,
g;g=c.camelCase(b);b=c.cssProps[g]||(c.cssProps[g]=nb(a.style,g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,true,e));f===k&&(f=G(a,b));f==="normal"&&b in gc&&(f=gc[b]);if(d||e!==k){a=parseFloat(f);return d||c.isNumeric(a)?a||0:f}return f},swap:function(a,b,d){var c,f={};for(c in b){f[c]=a.style[c];a.style[c]=b[c]}d=d.call(a);for(c in b)a.style[c]=f[c];return d}});l.getComputedStyle?G=function(a,b){var d,e,f,g,h=l.getComputedStyle(a,null),i=a.style;if(h){d=h[b];d===""&&!c.contains(a.ownerDocument,
a)&&(d=c.style(a,b));if(oa.test(d)&&fc.test(b)){e=i.width;f=i.minWidth;g=i.maxWidth;i.minWidth=i.maxWidth=i.width=d;d=h.width;i.width=e;i.minWidth=f;i.maxWidth=g}}return d}:o.documentElement.currentStyle&&(G=function(a,b){var c,e,f=a.currentStyle&&a.currentStyle[b],g=a.style;f==null&&(g&&g[b])&&(f=g[b]);if(oa.test(f)&&!sd.test(b)){c=g.left;if(e=a.runtimeStyle&&a.runtimeStyle.left)a.runtimeStyle.left=a.currentStyle.left;g.left=b==="fontSize"?"1em":f;f=g.pixelLeft+"px";g.left=c;if(e)a.runtimeStyle.left=
e}return f===""?"auto":f});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return a.offsetWidth===0&&td.test(G(a,"display"))?c.swap(a,vd,function(){return tb(a,b,f)}):tb(a,b,f)},set:function(a,e,f){return w(a,e,f?sb(a,b,f,c.support.boxSizing&&c.css(a,"boxSizing")==="border-box"):0)}}});c.support.opacity||(c.cssHooks.opacity={get:function(a,b){return rd.test((b&&a.currentStyle?a.currentStyle.filter:a.style.filter)||"")?0.01*parseFloat(RegExp.$1)+"":b?"1":""},set:function(a,
b){var d=a.style,e=a.currentStyle,f=c.isNumeric(b)?"alpha(opacity="+b*100+")":"",g=e&&e.filter||d.filter||"";d.zoom=1;if(b>=1&&c.trim(g.replace(jb,""))===""&&d.removeAttribute){d.removeAttribute("filter");if(e&&!e.filter)return}d.filter=jb.test(g)?g.replace(jb,f):g+" "+f}});c(function(){if(!c.support.reliableMarginRight)c.cssHooks.marginRight={get:function(a,b){return c.swap(a,{display:"inline-block"},function(){if(b)return G(a,"marginRight")})}};!c.support.pixelPosition&&c.fn.position&&c.each(["top",
"left"],function(a,b){c.cssHooks[b]={get:function(a,e){if(e){var f=G(a,b);return oa.test(f)?c(a).position()[b]+"px":f}}}})});c.expr&&c.expr.filters&&(c.expr.filters.hidden=function(a){return a.offsetWidth===0&&a.offsetHeight===0||!c.support.reliableHiddenOffsets&&(a.style&&a.style.display||G(a,"display"))==="none"},c.expr.filters.visible=function(a){return!c.expr.filters.hidden(a)});c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){for(var e=typeof c===
"string"?c.split(" "):[c],f={},c=0;c<4;c++)f[a+W[c]+b]=e[c]||e[c-2]||e[0];return f}};if(!fc.test(a))c.cssHooks[a+b].set=w});var xd=/%20/g,tc=/\[\]$/,hc=/\r?\n/g,yd=/^(?:color|date|datetime|datetime-local|email|hidden|month|number|password|range|search|tel|text|time|url|week)$/i,zd=/^(?:select|textarea)/i;c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){return this.elements?c.makeArray(this.elements):this}).filter(function(){return this.name&&
!this.disabled&&(this.checked||zd.test(this.nodeName)||yd.test(this.type))}).map(function(a,b){var d=c(this).val();return d==null?null:c.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(hc,"\r\n")}}):{name:b.name,value:d.replace(hc,"\r\n")}}).get()}});c.param=function(a,b){var d,e=[],f=function(a,b){b=c.isFunction(b)?b():b==null?"":b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(b)};b===k&&(b=c.ajaxSettings&&c.ajaxSettings.traditional);if(c.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,
function(){f(this.name,this.value)});else for(d in a)Oa(d,a[d],b,f);return e.join("&").replace(xd,"+")};var ia,ca,Ad=/#.*$/,Bd=/^(.*?):[ \t]*([^\r\n]*)\r?$/mg,Cd=/^(?:GET|HEAD)$/,Dd=/^\/\//,ic=/\?/,Ed=/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,Fd=/([?&])_=[^&]*/,jc=/^([\w\+\.\-]+:)(?:\/\/([^\/?#:]*)(?::(\d+)|)|)/,kc=c.fn.load,Pa={},lc={},mc=["*/"]+["*"];try{ca=vc.href}catch(Od){ca=o.createElement("a"),ca.href="",ca=ca.href}ia=jc.exec(ca.toLowerCase())||[];c.fn.load=function(a,b,d){if(typeof a!==
"string"&&kc)return kc.apply(this,arguments);if(!this.length)return this;var e,f,g,h=this,i=a.indexOf(" ");if(i>=0){e=a.slice(i,a.length);a=a.slice(0,i)}if(c.isFunction(b)){d=b;b=k}else b&&typeof b==="object"&&(f="POST");c.ajax({url:a,type:f,dataType:"html",data:b,complete:function(a,b){d&&h.each(d,g||[a.responseText,b,a])}}).done(function(a){g=arguments;h.html(e?c("<div>").append(a.replace(Ed,"")).find(e):a)});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),
function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){if(c.isFunction(e)){g=g||f;f=e;e=k}return c.ajax({type:b,url:a,data:e,success:f,dataType:g})}});c.extend({getScript:function(a,b){return c.get(a,k,b,"script")},getJSON:function(a,b,d){return c.get(a,b,d,"json")},ajaxSetup:function(a,b){if(b)vb(a,c.ajaxSettings);else{b=a;a=c.ajaxSettings}vb(a,b);return a},ajaxSettings:{url:ca,isLocal:/^(?:about|app|app\-storage|.+\-extension|file|res|widget):$/.test(ia[1]),
global:!0,type:"GET",contentType:"application/x-www-form-urlencoded; charset=UTF-8",processData:!0,async:!0,accepts:{xml:"application/xml, text/xml",html:"text/html",text:"text/plain",json:"application/json, text/javascript","*":mc},contents:{xml:/xml/,html:/html/,json:/json/},responseFields:{xml:"responseXML",text:"responseText"},converters:{"* text":l.String,"text html":!0,"text json":c.parseJSON,"text xml":c.parseXML},flatOptions:{context:!0,url:!0}},ajaxPrefilter:ub(Pa),ajaxTransport:ub(lc),ajax:function(a,
b){function d(a,b,d,g){var j,l,q,z,u=b;if(x!==2){x=2;i&&clearTimeout(i);h=k;f=g||"";y.readyState=a>0?4:0;if(d){z=n;var g=y,v,t,A,C,E=z.contents,D=z.dataTypes,G=z.responseFields;for(t in G)t in d&&(g[G[t]]=d[t]);for(;D[0]==="*";){D.shift();v===k&&(v=z.mimeType||g.getResponseHeader("content-type"))}if(v)for(t in E)if(E[t]&&E[t].test(v)){D.unshift(t);break}if(D[0]in d)A=D[0];else{for(t in d){if(!D[0]||z.converters[t+" "+D[0]]){A=t;break}C||(C=t)}A=A||C}if(A){A!==D[0]&&D.unshift(A);z=d[A]}else z=void 0}if(a>=
200&&a<300||a===304){if(n.ifModified){(d=y.getResponseHeader("Last-Modified"))&&(c.lastModified[e]=d);(d=y.getResponseHeader("Etag"))&&(c.etag[e]=d)}if(a===304){u="notmodified";j=true}else{a:{l=n;q=z;var B,F,u=l.dataTypes.slice();v=u[0];t={};A=0;l.dataFilter&&(q=l.dataFilter(q,l.dataType));if(u[1])for(B in l.converters)t[B.toLowerCase()]=l.converters[B];for(;d=u[++A];)if(d!=="*"){if(v!=="*"&&v!==d){B=t[v+" "+d]||t["* "+d];if(!B)for(F in t){j=F.split(" ");if(j[1]===d)if(B=t[v+" "+j[0]]||t["* "+j[0]]){if(B===
true)B=t[F];else if(t[F]!==true){d=j[0];u.splice(A--,0,d)}break}}if(B!==true)if(B&&l["throws"])q=B(q);else try{q=B(q)}catch(H){j={state:"parsererror",error:B?H:"No conversion from "+v+" to "+d};break a}}v=d}j={state:"success",data:q}}u=j.state;l=j.data;q=j.error;j=!q}}else{q=u;if(!u||a){u="error";a<0&&(a=0)}}y.status=a;y.statusText=(b||u)+"";j?r.resolveWith(o,[l,u,y]):r.rejectWith(o,[y,u,q]);y.statusCode(w);w=k;m&&s.trigger("ajax"+(j?"Success":"Error"),[y,n,j?l:q]);p.fireWith(o,[y,u]);if(m){s.trigger("ajaxComplete",
[y,n]);--c.active||c.event.trigger("ajaxStop")}}}if(typeof a==="object"){b=a;a=k}var b=b||{},e,f,g,h,i,j,m,l,n=c.ajaxSetup({},b),o=n.context||n,s=o!==n&&(o.nodeType||o instanceof c)?c(o):c.event,r=c.Deferred(),p=c.Callbacks("once memory"),w=n.statusCode||{},z={},u={},x=0,v="canceled",y={readyState:0,setRequestHeader:function(a,b){if(!x){var c=a.toLowerCase(),a=u[c]=u[c]||a;z[a]=b}return this},getAllResponseHeaders:function(){return x===2?f:null},getResponseHeader:function(a){var b;if(x===2){if(!g)for(g=
{};b=Bd.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return b===k?null:b},overrideMimeType:function(a){if(!x)n.mimeType=a;return this},abort:function(a){a=a||v;h&&h.abort(a);d(0,a);return this}};r.promise(y);y.success=y.done;y.error=y.fail;y.complete=p.add;y.statusCode=function(a){if(a){var b;if(x<2)for(b in a)w[b]=[w[b],a[b]];else{b=a[y.status];y.always(b)}}return this};n.url=((a||n.url)+"").replace(Ad,"").replace(Dd,ia[1]+"//");n.dataTypes=c.trim(n.dataType||"*").toLowerCase().split(X);
if(n.crossDomain==null){j=jc.exec(n.url.toLowerCase())||false;n.crossDomain=j&&j.join(":")+(j[3]?"":j[1]==="http:"?80:443)!==ia.join(":")+(ia[3]?"":ia[1]==="http:"?80:443)}if(n.data&&n.processData&&typeof n.data!=="string")n.data=c.param(n.data,n.traditional);pa(Pa,n,b,y);if(x===2)return y;m=n.global;n.type=n.type.toUpperCase();n.hasContent=!Cd.test(n.type);m&&c.active++===0&&c.event.trigger("ajaxStart");if(!n.hasContent){if(n.data){n.url=n.url+((ic.test(n.url)?"&":"?")+n.data);delete n.data}e=n.url;
if(n.cache===false){j=c.now();var t=n.url.replace(Fd,"$1_="+j);n.url=t+(t===n.url?(ic.test(n.url)?"&":"?")+"_="+j:"")}}(n.data&&n.hasContent&&n.contentType!==false||b.contentType)&&y.setRequestHeader("Content-Type",n.contentType);if(n.ifModified){e=e||n.url;c.lastModified[e]&&y.setRequestHeader("If-Modified-Since",c.lastModified[e]);c.etag[e]&&y.setRequestHeader("If-None-Match",c.etag[e])}y.setRequestHeader("Accept",n.dataTypes[0]&&n.accepts[n.dataTypes[0]]?n.accepts[n.dataTypes[0]]+(n.dataTypes[0]!==
"*"?", "+mc+"; q=0.01":""):n.accepts["*"]);for(l in n.headers)y.setRequestHeader(l,n.headers[l]);if(n.beforeSend&&(n.beforeSend.call(o,y,n)===false||x===2))return y.abort();v="abort";for(l in{success:1,error:1,complete:1})y[l](n[l]);if(h=pa(lc,n,b,y)){y.readyState=1;m&&s.trigger("ajaxSend",[y,n]);n.async&&n.timeout>0&&(i=setTimeout(function(){y.abort("timeout")},n.timeout));try{x=1;h.send(z,d)}catch(A){if(x<2)d(-1,A);else throw A;}}else d(-1,"No Transport");return y},active:0,lastModified:{},etag:{}});
var nc=[],Gd=/\?/,La=/(=)\?(?=&|$)|\?\?/,Hd=c.now();c.ajaxSetup({jsonp:"callback",jsonpCallback:function(){var a=nc.pop()||c.expando+"_"+Hd++;this[a]=true;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f,g,h=a.data,i=a.url,j=a.jsonp!==false,m=j&&La.test(i),o=j&&!m&&typeof h==="string"&&!(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&La.test(h);if(a.dataTypes[0]==="jsonp"||m||o){e=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f=l[e];
if(m)a.url=i.replace(La,"$1"+e);else if(o)a.data=h.replace(La,"$1"+e);else if(j)a.url=a.url+((Gd.test(i)?"&":"?")+a.jsonp+"="+e);a.converters["script json"]=function(){g||c.error(e+" was not called");return g[0]};a.dataTypes[0]="json";l[e]=function(){g=arguments};d.always(function(){l[e]=f;if(a[e]){a.jsonpCallback=b.jsonpCallback;nc.push(e)}g&&c.isFunction(f)&&f(g[0]);g=f=k});return"script"}});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},
contents:{script:/javascript|ecmascript/},converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){if(a.cache===k)a.cache=false;if(a.crossDomain){a.type="GET";a.global=false}});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,c=o.head||o.getElementsByTagName("head")[0]||o.documentElement;return{send:function(e,f){b=o.createElement("script");b.async="async";if(a.scriptCharset)b.charset=a.scriptCharset;b.src=a.url;b.onload=b.onreadystatechange=
function(a,e){if(e||!b.readyState||/loaded|complete/.test(b.readyState)){b.onload=b.onreadystatechange=null;c&&b.parentNode&&c.removeChild(b);b=k;e||f(200,"success")}};c.insertBefore(b,c.firstChild)},abort:function(){if(b)b.onload(0,1)}}}});var ja,kb=l.ActiveXObject?function(){for(var a in ja)ja[a](0,1)}:!1,Id=0;c.ajaxSettings.xhr=l.ActiveXObject?function(){var a;if(!(a=!this.isLocal&&wb()))a:{try{a=new l.ActiveXObject("Microsoft.XMLHTTP");break a}catch(b){}a=void 0}return a}:wb;var lb=c.ajaxSettings.xhr();
c.extend(c.support,{ajax:!!lb,cors:!!lb&&"withCredentials"in lb});c.support.ajax&&c.ajaxTransport(function(a){if(!a.crossDomain||c.support.cors){var b;return{send:function(d,e){var f,g,h=a.xhr();a.username?h.open(a.type,a.url,a.async,a.username,a.password):h.open(a.type,a.url,a.async);if(a.xhrFields)for(g in a.xhrFields)h[g]=a.xhrFields[g];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);!a.crossDomain&&!d["X-Requested-With"]&&(d["X-Requested-With"]="XMLHttpRequest");try{for(g in d)h.setRequestHeader(g,
d[g])}catch(i){}h.send(a.hasContent&&a.data||null);b=function(d,g){var i,n,l,o,s;try{if(b&&(g||h.readyState===4)){b=k;if(f){h.onreadystatechange=c.noop;kb&&delete ja[f]}if(g)h.readyState!==4&&h.abort();else{i=h.status;l=h.getAllResponseHeaders();o={};if((s=h.responseXML)&&s.documentElement)o.xml=s;try{o.text=h.responseText}catch(r){}try{n=h.statusText}catch(p){n=""}!i&&a.isLocal&&!a.crossDomain?i=o.text?200:404:i===1223&&(i=204)}}}catch(t){g||e(-1,t)}o&&e(i,n,o,l)};if(a.async)if(h.readyState===4)setTimeout(b,
0);else{f=++Id;if(kb){if(!ja){ja={};c(l).unload(kb)}ja[f]=b}h.onreadystatechange=b}else b()},abort:function(){b&&b(0,1)}}}});var qa,Ma,Jd=/^(?:toggle|show|hide)$/,Kd=RegExp("^(?:([-+])=|)("+ua+")([a-z%]*)$","i"),Ld=/queueHooks$/,ra=[function(a,b,d){var e,f,g,h,i,j,k=this,l=a.style,n={},o=[],s=a.nodeType&&P(a);if(!d.queue){i=c._queueHooks(a,"fx");if(i.unqueued==null){i.unqueued=0;j=i.empty.fire;i.empty.fire=function(){i.unqueued||j()}}i.unqueued++;k.always(function(){k.always(function(){i.unqueued--;
c.queue(a,"fx").length||i.empty.fire()})})}if(a.nodeType===1&&("height"in b||"width"in b)){d.overflow=[l.overflow,l.overflowX,l.overflowY];if(c.css(a,"display")==="inline"&&c.css(a,"float")==="none")!c.support.inlineBlockNeedsLayout||rb(a.nodeName)==="inline"?l.display="inline-block":l.zoom=1}if(d.overflow){l.overflow="hidden";c.support.shrinkWrapBlocks||k.done(function(){l.overflow=d.overflow[0];l.overflowX=d.overflow[1];l.overflowY=d.overflow[2]})}for(e in b){f=b[e];if(Jd.exec(f)){delete b[e];f!==
(s?"hide":"show")&&o.push(e)}}if(f=o.length){g=c._data(a,"fxshow")||c._data(a,"fxshow",{});s?c(a).show():k.done(function(){c(a).hide()});k.done(function(){var b;c.removeData(a,"fxshow",true);for(b in n)c.style(a,b,n[b])});for(e=0;e<f;e++){b=o[e];h=k.createTween(b,s?g[b]:0);n[b]=g[b]||c.style(a,b);if(!(b in g)){g[b]=h.start;if(s){h.end=h.start;h.start=b==="width"||b==="height"?1:0}}}}}],ka={"*":[function(a,b){var d,e,f=this.createTween(a,b),g=Kd.exec(b),h=f.cur(),i=+h||0,j=1,k=20;if(g){d=+g[2];e=g[3]||
(c.cssNumber[a]?"":"px");if(e!=="px"&&i){i=c.css(f.elem,a,true)||d||1;do{j=j||".5";i=i/j;c.style(f.elem,a,i+e)}while(j!==(j=f.cur()/h)&&j!==1&&--k)}f.unit=e;f.start=i;f.end=g[1]?i+(g[1]+1)*d:d}return f}]};c.Animation=c.extend(yb,{tweener:function(a,b){if(c.isFunction(a)){b=a;a=["*"]}else a=a.split(" ");for(var d,e=0,f=a.length;e<f;e++){d=a[e];ka[d]=ka[d]||[];ka[d].unshift(b)}},prefilter:function(a,b){b?ra.unshift(a):ra.push(a)}});c.Tween=H;H.prototype={constructor:H,init:function(a,b,d,e,f,g){this.elem=
a;this.prop=d;this.easing=f||"swing";this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=H.propHooks[this.prop];return a&&a.get?a.get(this):H.propHooks._default.get(this)},run:function(a){var b,d=H.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&this.options.step.call(this.elem,this.now,
this);d&&d.set?d.set(this):H.propHooks._default.set(this);return this}};H.prototype.init.prototype=H.prototype;H.propHooks={_default:{get:function(a){if(a.elem[a.prop]!=null&&(!a.elem.style||a.elem.style[a.prop]==null))return a.elem[a.prop];a=c.css(a.elem,a.prop,false,"");return!a||a==="auto"?0:a},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else a.elem.style&&(a.elem.style[c.cssProps[a.prop]]!=null||c.cssHooks[a.prop])?c.style(a.elem,a.prop,a.now+a.unit):a.elem[a.prop]=a.now}}};H.propHooks.scrollTop=
H.propHooks.scrollLeft={set:function(a){if(a.elem.nodeType&&a.elem.parentNode)a.elem[a.prop]=a.now}};c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(e,f,g){return e==null||typeof e==="boolean"||!a&&c.isFunction(e)&&c.isFunction(f)?d.apply(this,arguments):this.animate(sa(b,true),e,f,g)}});c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(P).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,
e),b=function(){var b=yb(this,c.extend({},a),g);f&&b.stop(true)};return f||g.queue===false?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};if(typeof a!=="string"){d=b;b=a;a=k}b&&a!==false&&this.queue(a||"fx",[]);return this.each(function(){var b=true,g=a!=null&&a+"queueHooks",h=c.timers,i=c._data(this);if(g)i[g]&&i[g].stop&&e(i[g]);else for(g in i)i[g]&&(i[g].stop&&Ld.test(g))&&e(i[g]);for(g=h.length;g--;)if(h[g].elem===this&&(a==null||h[g].queue===
a)){h[g].anim.stop(d);b=false;h.splice(g,1)}(b||!d)&&c.dequeue(this,a)})}});c.each({slideDown:sa("show"),slideUp:sa("hide"),slideToggle:sa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.speed=function(a,b,d){var e=a&&typeof a==="object"?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};e.duration=c.fx.off?0:typeof e.duration==="number"?
e.duration:e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default;if(e.queue==null||e.queue===true)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&c.dequeue(this,e.queue)};return e};c.easing={linear:function(a){return a},swing:function(a){return 0.5-Math.cos(a*Math.PI)/2}};c.timers=[];c.fx=H.prototype.init;c.fx.tick=function(){for(var a,b=c.timers,d=0;d<b.length;d++){a=b[d];!a()&&b[d]===a&&b.splice(d--,1)}b.length||c.fx.stop()};c.fx.timer=
function(a){a()&&(c.timers.push(a)&&!Ma)&&(Ma=setInterval(c.fx.tick,c.fx.interval))};c.fx.interval=13;c.fx.stop=function(){clearInterval(Ma);Ma=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fx.step={};c.expr&&c.expr.filters&&(c.expr.filters.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length});var oc=/^(?:body|html)$/i;c.fn.offset=function(a){if(arguments.length)return a===k?this:this.each(function(b){c.offset.setOffset(this,a,b)});var b,d,e,f,g,h={top:0,left:0};
if(e=(f=this[0])&&f.ownerDocument){if((d=e.body)===f)return c.offset.bodyOffset(f);b=e.documentElement;if(!c.contains(b,f))return h;typeof f.getBoundingClientRect!=="undefined"&&(h=f.getBoundingClientRect());e=zb(e);f=b.clientTop||d.clientTop||0;d=b.clientLeft||d.clientLeft||0;g=e.pageYOffset||b.scrollTop;b=e.pageXOffset||b.scrollLeft;return{top:h.top+g-f,left:h.left+b-d}}};c.offset={bodyOffset:function(a){var b=a.offsetTop,d=a.offsetLeft;if(c.support.doesNotIncludeMarginInBodyOffset){b=b+(parseFloat(c.css(a,
"marginTop"))||0);d=d+(parseFloat(c.css(a,"marginLeft"))||0)}return{top:b,left:d}},setOffset:function(a,b,d){var e=c.css(a,"position");if(e==="static")a.style.position="relative";var f=c(a),g=f.offset(),h=c.css(a,"top"),i=c.css(a,"left"),j={},k={};if((e==="absolute"||e==="fixed")&&c.inArray("auto",[h,i])>-1){k=f.position();e=k.top;i=k.left}else{e=parseFloat(h)||0;i=parseFloat(i)||0}c.isFunction(b)&&(b=b.call(a,d,g));if(b.top!=null)j.top=b.top-g.top+e;if(b.left!=null)j.left=b.left-g.left+i;"using"in
b?b.using.call(a,j):f.css(j)}};c.fn.extend({position:function(){if(this[0]){var a=this[0],b=this.offsetParent(),d=this.offset(),e=oc.test(b[0].nodeName)?{top:0,left:0}:b.offset();d.top=d.top-(parseFloat(c.css(a,"marginTop"))||0);d.left=d.left-(parseFloat(c.css(a,"marginLeft"))||0);e.top=e.top+(parseFloat(c.css(b[0],"borderTopWidth"))||0);e.left=e.left+(parseFloat(c.css(b[0],"borderLeftWidth"))||0);return{top:d.top-e.top,left:d.left-e.left}}},offsetParent:function(){return this.map(function(){for(var a=
this.offsetParent||o.body;a&&!oc.test(a.nodeName)&&c.css(a,"position")==="static";)a=a.offsetParent;return a||o.body})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d=/Y/.test(b);c.fn[a]=function(e){return c.access(this,function(a,e,h){var i=zb(a);if(h===k)return i?b in i?i[b]:i.document.documentElement[e]:a[e];i?i.scrollTo(!d?h:c(i).scrollLeft(),d?h:c(i).scrollTop()):a[e]=h},a,e,arguments.length,null)}});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+
a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(e,g){var h=arguments.length&&(d||typeof e!=="boolean"),i=d||(e===true||g===true?"margin":"border");return c.access(this,function(b,d,e){if(c.isWindow(b))return b.document.documentElement["client"+a];if(b.nodeType===9){d=b.documentElement;return Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])}return e===k?c.css(b,d,e,i):c.style(b,d,e,i)},b,h?e:k,h,null)}})});l.jQuery=l.$=c;"function"===typeof define&&
(define.amd&&define.amd.jQuery)&&define("jquery",[],function(){return c})})(window);
(function(l){"$:nomunge";var k,A,p=1,v,r=this,F,V=r.postMessage&&!l.browser.opera;l.postMessage=function(k,r,v){r&&(k="string"===typeof k?k:l.param(k),v=v||parent,V?v.postMessage(k,r.replace(/([^:]+:\/\/[^\/]+).*/,"$1")):r&&(v.location=r.replace(/#.*$/,"")+"#"+ +new Date+p++ +"&"+k))};l.receiveMessage=F=function(p,B,R){if(V)if(p&&(v&&F(),v=function(k){if("string"===typeof B&&k.origin!==B||l.isFunction(B)&&!1===B(k.origin))return!1;p(k)}),r.addEventListener)r[p?"addEventListener":"removeEventListener"]("message",
v,!1);else r[p?"attachEvent":"detachEvent"]("onmessage",v);else k&&clearInterval(k),k=null,p&&(k=setInterval(function(){var k=document.location.hash,l=/^#?\d+&/;k!==A&&l.test(k)&&(A=k,p({data:k.replace(l,"")}))},"number"===typeof B?B:"number"===typeof R?R:100))}})(jQuery);
$(function(){var l,k;(k=$("body").attr("data-parent_href"))&&($.browser.msie&&7===parseFloat($.browser.version)&&"#"!==k.charAt(k.length-1))&&(k+="#");l=function(l){"string"!==typeof l&&(l=JSON.stringify(l));$.postMessage(l,k,parent)};$.receiveMessage(function(A){var p;if(A.origin===k||$.browser.msie&&7===parseFloat($.browser.version)){try{p=JSON.parse(A.data)}catch(v){p=A.data}p&&"object"===typeof p&&"metric:mixpanel"===p.act?mixpanel.push([p.operation||"track",p.event,p.mp_properties]):$.post("/message_handler",
p,function(k){k&&l(k)},"json")}},k)});
